### ISSUE TITLE
user can leak sensitive data if used within a loop 

### ISSUE THREAD

**Issue by rht-jbittner** [theforeman/foreman-ansible-modules#1006]
##### SUMMARY

It is basically the same situation like with compute_resource. If user module is used in a loop, it will leak passwords.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.13
```

##### KATELLO/FOREMAN VERSION

```
tfm-rubygem-katello-3.14.0.20-1.el7sat.noarch
foreman-1.24.1.21-1.el7sat.noarch
```

##### APYPIE VERSION

```
Metadata-Version: 1.1
Version: 0.2.0
```

##### STEPS TO REPRODUCE

```yaml
redhat.satellite.user:
    username: "{{ satellite_api_user }}"
    password: "{{ satellite_api_password }}"
    server_url: "https://{{ inventory_hostname }}"
    name: "{{ item.name }}"
    mail: "{{ item.mail }}"
    admin: "{{ item.admin | default('no') }}"
    user_password: "{{ item.user_password | default(omit) }}"
    auth_source: "{{ item.auth_source }}"
    roles: "{{ item.roles | default(omit) }}"
    locations: "{{ item.locations | default(omit) }}"
    organizations: "{{ item.organizations | default(omit) }}"
    state: present
  with_items: "{{ satellite_users }}"

```

##### EXPECTED RESULTS

Pasword should not leak
##### ACTUAL RESULTS

Password leaked

```
changed: [satellite.test.example.local] => (item={u'organizations': [u'Test'], u'name': u'Test_user', u'auth_source': u'Internal', u'admin': True, u'mail': u'testuseremail@example.local', u'user_password': u'some_strong_password', u'locations': [u'loc1', u'Loc2']})
```
