### ISSUE TITLE
Module defaults groups

### ISSUE THREAD

**Issue by markgraf** [theforeman/foreman-ansible-modules#1015]
##### SUMMARY
As it is now, there are 54 modules that all want
- user
- password
- server-url

Repeating those same informations over and over again with all the modules you use is lots of redundant work.
Creating "module defaults" for each of them is equally redundant.

##### FEATURE REQUEST
 It would be nice to have [Module defaults groups](https://docs.ansible.com/ansible/latest/user_guide/playbooks_module_defaults.html#module-defaults-groups) in order to define that block ONCE for an entire playbook like this:

```
# example_play.yml
- hosts: localhost
  module_defaults:
    group/foreman:
      name: myNameIs
      password: TopS3cr3t
      server_url: foreman.at.home
```
These already exist for aws, azure, gcp, etc..., so I guess most of the needed code should already exist?
