### ISSUE TITLE
parameters: add option "hidden" to parameters to not show values in gui

### ISSUE THREAD

**Issue by fgoebel** [theforeman/foreman-ansible-modules#1024]
- [x] global_parameter
- [ ] smart_class_parameter
- [ ] nested parameter (org, loc)
- [ ] domain, subnet, host, hostgroup, ... ("direct" params, for the lack of a better name)

##### SUMMARY
When I set parameters with these modules (global_parameters, organizations, locations,...) it is not possible to toggle the "hidden" option like in the gui.

```
# task example:
- theforeman.foreman.location:
    username: "{{ foreman_web_user }}"
    password: "{{ foreman_web_password }}"
    server_url: "{{ foreman_server }}"
    name: "some location"
    organizations:
    - "some Org"
    state: present
    parameters:
      - name: password
        parameter_type: string
        value: verySecretPasswordIdoNotWantToShowInGui
        hidden: true
```

What do you think?

##### ISSUE TYPE
 - Feature Idea
