### ISSUE TITLE
theforeman.foreman.content_upload fails with error "non_field_errors: Chunk size does not match content range."

### ISSUE THREAD

**Issue by pescobar** [theforeman/foreman-ansible-modules#1043]
##### SUMMARY

`theforeman.foreman.content_upload` fails with error `"non_field_errors: Chunk size does not match content range."` when uploading [this binary file](https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64)

The same tasks works ok when uploading a small txt file instead of a binary file

The file triggering the error can be uploaded using hammer doing `hammer repository upload-content --organization-id 1 --id 1548 --content-type file --path /tmp/docker-compose-Linux-x86_64`  . Hammer upload test is done from the same host where katello is running. Ansible task triggering the error is executed from a different host.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.10.2
  config file = /home/escobar/ansible/playbooks/ansible-playbook-foreman-katello/ansible.cfg
  configured module search path = ['/home/escobar/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/escobar/tmp/venv_ansible_2.10.2/lib/python3.6/site-packages/ansible
  executable location = /home/escobar/tmp/venv_ansible_2.10.2/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]

```

##### COLLECTION VERSION
```
# /home/escobar/ansible/playbooks/ansible-playbook-foreman-katello/collections/ansible_collections
Collection         Version
------------------ -------
theforeman.foreman 1.4.0
```

##### KATELLO/FOREMAN VERSION
```
tfm-rubygem-katello-3.16.0-1.el7.noarch
foreman-2.1.2-1.el7.noarch
```

##### STEPS TO REPRODUCE

```
wget -P /tmp/ https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
```

```yaml
- name: "Create product 'docker-compose'"
  theforeman.foreman.product:
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_url }}"
    validate_certs: "{{ foreman_validate_certs }}"
    organization: "{{ foreman_initial_organization }}"
    name: "docker-compose"
    state: present

- name: "Create files repository 'docker-compose-linux-x86_64' for product 'docker-compose'"
  theforeman.foreman.repository:
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_url }}"
    validate_certs: "{{ foreman_validate_certs }}"
    organization: "{{ foreman_initial_organization }}"
    name: "docker-compose-linux-x86_64"
    state: present
    content_type: "file"
    product: "docker-compose"
  register: _repo_info

- name: "Upload a test file"
  theforeman.foreman.content_upload:
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_url }}"
    validate_certs: "{{ foreman_validate_certs }}"
    organization: "{{ foreman_initial_organization }}"
    src: "/tmp/docker-compose-Linux-x86_64"
    #src: "/tmp/lele.txt"
    product: "docker-compose"
    repository: "docker-compose-linux-x86_64"

```

##### EXPECTED RESULTS

File should be uploaded to the repository but it fails. The same task works OK when uploading a small txt file. e.g

```
echo "test" > /tmp/lelele.txt
```

```yaml
- name: "Upload a test file"
  theforeman.foreman.content_upload:
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_url }}"
    validate_certs: "{{ foreman_validate_certs }}"
    organization: "{{ foreman_initial_organization }}"
    src: "/tmp/lelele.txt"
    product: "docker-compose"
    repository: "docker-compose-linux-x86_64"
```
