### ISSUE TITLE
[WARNING]: The following parameters are not supported by your server when performing create on repositories: {'organization_id'}. They were ignored.

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#1055]
##### SUMMARY
trying to create a repo using the below playbook

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.10
```

##### COLLECTION VERSION

```
develop
```

##### KATELLO/FOREMAN VERSION

```
3.16
```

##### STEPS TO REPRODUCE

```yaml
    - name: "Create files repository 'docker-compose-linux-x86_64' for product 'docker-compose'"
      theforeman.foreman.repository:
        username: "{{ foreman_username }}"
        password: "{{ foreman_password }}"
        server_url: "{{ foreman_url }}"
        validate_certs: "{{ foreman_validate_certs }}"
        organization: "{{ foreman_initial_organization }}"
        name: "docker-compose-linux-x86_64"
        state: present
        content_type: "file"
        product: "docker-compose"

```

##### EXPECTED RESULTS

no warning

##### ACTUAL RESULTS

```

```
