### ISSUE TITLE
Idempotence not working in Foreman 1.12.4 when using parameters attributes

### ISSUE THREAD

**Issue by piascwal** [theforeman/foreman-ansible-modules#1103]
##### SUMMARY
Idempotence not working in Foreman 1.12.4 when using parameters attributes in theforeman.foreman.host Ansible module

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.12
  config file = None
  configured module search path = ['/home/myhome/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /xxxx/lib/python3.6/site-packages/ansible
  executable location = /xxx/bin/ansible
  python version = 3.6.8 (default, Oct  7 2019, 17:58:22) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]
```

##### COLLECTION VERSION

```
theforeman.foreman
1.5.1
```

##### STEPS TO REPRODUCE
Foreman version 1.12.4

```yaml
- name: "Add host to foreman"
  theforeman.foreman.host:
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_server_url }}"
    name: "{{ inventory_hostname }}"
    hostgroup: "{{ foreman_hostgroup }}"
    operatingsystem: "{{ foreman_operatingsystem }}"
    organization: "{{ foreman_organization }}"
    domain: "{{ inventory_hostname.split('.')[1:] | join('.') }}"
    architecture: "{{ foreman_architecture }}"
    puppetclasses: "{{ puppetclasses | default(omit) }}"
    parameters: [
        {
            "name": "foo1",
            "value": "bar1"
        },
        {
            "name": "foo2",
            "value": "bar2"
        }
    ]
    build: "{{ foreman_build }}"
    managed: "{{foreman_managed}}"
    location: "{{ foreman_location }}"
    validate_certs: False
    state: "{{ foreman_state | default(omit) }}"
  delegate_to: localhost
```

##### EXPECTED RESULTS
Idempotence on seconde execution

##### ACTUAL RESULTS

The first execution is working but second failed

The same task is working when module call Foreman 2.0.1 API
The task with `parameter: []` is working with idempotence when calling Foreman 1.12.4

Even if problem is solved, when I modify `parameters_list_to_str_list` in `foreman_helper.py`
by setting new_param['parameter_type']='string'
Foreman return that my propertie already exists.
I know that, and what i need is to override it if necessary

```
Traceback (most recent call last):
  File \"/home/myhome/.ansible/tmp/ansible-tmp-1608129849.723493-17208-93215851431458/AnsiballZ_host.py\", line 102, in <module>
    _ansiballz_main()
  File \"/home/myhome/.ansible/tmp/ansible-tmp-1608129849.723493-17208-93215851431458/AnsiballZ_host.py\", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/home/myhome/.ansible/tmp/ansible-tmp-1608129849.723493-17208-93215851431458/AnsiballZ_host.py\", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.theforeman.foreman.plugins.modules.host', init_globals=None, run_name='__main__', alter_sys=True)
  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code
    exec(code, run_globals)
  File \"/tmp/ansible_theforeman.foreman.host_payload_xi2eln0n/ansible_theforeman.foreman.host_payload.zip/ansible_collections/theforeman/foreman/plugins/modules/host.py\", line 505, in <module>
  File \"/tmp/ansible_theforeman.foreman.host_payload_xi2eln0n/ansible_theforeman.foreman.host_payload.zip/ansible_collections/theforeman/foreman/plugins/modules/host.py\", line 495, in main
  File \"/tmp/ansible_theforeman.foreman.host_payload_xi2eln0n/ansible_theforeman.foreman.host_payload.zip/ansible_collections/theforeman/foreman/plugins/module_utils/foreman_helper.py\", line 194, in run
  File \"/tmp/ansible_theforeman.foreman.host_payload_xi2eln0n/ansible_theforeman.foreman.host_payload.zip/ansible_collections/theforeman/foreman/plugins/module_utils/foreman_helper.py\", line 1561, in parameters_list_to_str_list
KeyError: 'parameter_type'
", "module_stdout": "", "msg": "MODULE FAILURE
See stdout/stderr for the exact error", "rc": 1}
```
