### ISSUE TITLE
Automatically match network_name to network_id for the deployement of new VM´s on VMWare

### ISSUE THREAD

**Issue by SimonLorentz** [theforeman/foreman-ansible-modules#1104]
##### SUMMARY

If I deploy a new Host over Foreman on my VMWare Cluster, with the host FAM, I need to manually check the correct network_id for my network or otherwise Foreman will always show a wrong network in the VM´s Interface tab.

Should be nearly the same like: https://github.com/theforeman/foreman-ansible-modules/issues/1041
##### ISSUE TYPE
 - Feature Idea

Automatically lookup the correct network_id for a network_name. I coul use as workaround the Ansible URI Module to do this, but, this is probably not the best solution, it would be better to implement it into the host FAM.

Here is an example of my workaround:

```
- name: Get network ids
  uri:
    url: "{{ foreman_server_url }}/api/compute_resources/{{ compute_ressource_id }}/available_networks"
    user: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    method: GET
    return_content: true
    force_basic_auth: true
    validate_certs: "{{ validate_foreman_certs }}"
  register: available_networks
  no_log: true

- set_fact:
    vsphere_network_id1: "{{ available_networks | json_query(query) | first }}"
  vars:
    query: "json.results[?name=='{{ foreman_host_vm.networkinterfaces[0].name }}'].id"
```
