### ISSUE TITLE
Unable to provision a host (with Libvirt/KVM) based on a qcow2 image without explicitly setting the image_id parameter.

### ISSUE THREAD

**Issue by MLotton** [theforeman/foreman-ansible-modules#1160]
##### SUMMARY
I wanted to provision a VM with a Libvirt/KVM compute ressource based on an image provision method with an existing qcow2 image. I encountered an issue where the host was created but the image provisioning wasn't correctly done by using the module `host`.
The result is not the same by using the hammer CLI or the foreman/satellite web UI (with identical input parameters).

Looking further and comparing with what was done by the Satellite Web UI and Hammer CLI, I found that the `host` module  (python code) doesn't send the `image_id` to the API call (Note: I didn't investigate a lot, so it is a guess). I tried again by adding the parameter `image_id` directly in the module parameters (inside `compute_attributes`) and then it worked well.

I guess that the Ansible module(s) / python code must perform an additional step to resolve the image_id based on the image name and send it to the API call (as it will be more user friendly if the user only has to put the image name as an input parameter).

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/max/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/max/deploy/venvs_python/ansible_epdb_python_2/lib/python2.7/site-packages/ansible
  executable location = /home/max/deploy/venvs_python/ansible_epdb_python_2/bin/ansible
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### COLLECTION VERSION
```
redhat.satellite:2.0.1
```
Repo link: https://github.com/RedHatSatellite/satellite-ansible-collection
This was not tested with the community foreman collection version.

##### KATELLO/FOREMAN VERSION
```
tfm-rubygem-katello-3.16.0.13-1.el7sat.noarch
foreman-2.1.2.21-1.el7sat.noarch
```

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  gather_facts: False
  tasks:

    - include_vars: input_variables/vault_secrets.yml

    - name: "Create Satellite host"
      theforeman.foreman.host:
        name: "example-host.example.com"
        architecture: "x86_64"
        build: True
        comment: "Test collection"
        domain: "example.com"
        interfaces_attributes:
          - subnet: "Example subnet provisioning"
            identifier: eth0
            type: interface
            domain: "example.com"
            managed: True
            primary: True
            provision: True
        location: "example_location"
        operatingsystem: "CentOS 7 Latest"
        organization: "example_organization"
        root_pass: "example_password"
        server_url: "https://satellite-host"
        username: "example_user"
        password: "{{ satellite_user_password }}"
        validate_certs: False
        state: present
        provision_method: image
        image: "my-vm-qcow2-image"
        compute_resource: "Example Libvirt ressource"
        compute_profile: "example-compute-profile"
```

##### EXPECTED RESULTS
The host is created and well provisioned based on a qcow2 image.

The boot device order is based only on the first disk.
Note: Satellite will also create a virtual CDROM device for user data / cloud-init (like this example, below you will find the definition of this device for libvirt/kvm in a XML format):
```
<disk type="file" device="cdrom">
  <driver name="qemu" type="raw"/>
  <source file="/var/lib/libvirt/images/example-host.example.com-cloud-init.iso"/>
  <backingStore/>
  <target dev="hdc" bus="ide"/>
  <readonly/>
  <alias name="ide0-1-0"/>
  <address type="drive" controller="0" bus="1" target="0" unit="0"/>
</disk>
```

##### ACTUAL RESULTS
The host is created but the VM is "blank" (no OS installed, etc).

The boot device order is first "network" and then "disk". 
There is no virtual CDROM device created.

##### WORKAROUND

```yaml
---
- hosts: localhost
  gather_facts: False
  tasks:

    - include_vars: input_variables/vault_secrets.yml

    - name: "Create Satellite host"
      theforeman.foreman.host:
        name: "example-host.example.com"
        architecture: "x86_64"
        build: True
        comment: "Test collection"
        domain: "example.com"
        interfaces_attributes:
          - subnet: "Example subnet provisioning"
            type: interface
            domain: "example.com"
            managed: True
            primary: True
            provision: True
        location: "example_location"
        operatingsystem: "CentOS 7 Latest"
        organization: "example_organization"
        root_pass: "example_password"
        server_url: "https://satellite-host"
        username: "example_user"
        password: "{{ satellite_user_password }}"
        validate_certs: False
        state: present
        provision_method: image
        image: "my-vm-qcow2-image"
        compute_resource: "Example Libvirt ressource"
        compute_profile: "example-compute-profile"
        compute_attributes:
          image_id: "/var/lib/libvirt/images/my-vm-qcow2-image.qcow2"
```
By adding:
```yaml
compute_attributes:
  image_id: "/var/lib/libvirt/images/my-vm-qcow2-image.qcow2"
```
It works as expected.
