### ISSUE TITLE
hostgroup update with puppetclasses or description

### ISSUE THREAD

**Issue by achevalet** [theforeman/foreman-ansible-modules#1231]
##### SUMMARY
Hi, I've some issues with the hostgroup module:
- it seems that `puppetclasses` cannot be updated
- updating `description` when passing `puppetclasses` fails
- `puppetclass_ids` is not returned at creation

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.10.6
  config file = None
  configured module search path = ['/home/neo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

```

##### COLLECTION VERSION

```
# /usr/local/lib/python3.6/site-packages/ansible_collections
Collection         Version
------------------ -------
theforeman.foreman 2.1.0  

```

##### KATELLO/FOREMAN VERSION

```
tfm-rubygem-katello-3.14.1-1.el7.noarch
foreman-1.24.3-1.el7.noarch

```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  collections:
    - theforeman.foreman
  gather_facts: false
  tasks:
    - name: Ensure Hostgroup '{{ name }}' is {{ state }}
      hostgroup:
        name: "{{ name }}"
        updated_name: "{{ updated_name | default(omit) }}"
        parent: "{{ parent | default(omit) }}"
        description: "{{ description | default(omit) }}"
        locations: "{{ locations | default(omit) }}"
        organizations: "{{ organizations | default(omit) }}"
        compute_resource: "{{ compute_resource | default(omit) }}"
        compute_profile: "{{ compute_profile | default(omit) }}"
        domain: "{{ domain | default(omit) }}"
        subnet: "{{ subnet | default(omit) }}"
        subnet6: "{{ subnet6 | default(omit) }}"
        realm: "{{ realm | default(omit) }}"
        architecture: "{{ architecture | default(omit) }}"
        operatingsystem: "{{ operatingsystem | default(omit) }}"
        medium: "{{ installation_medium | default(omit) }}"
        ptable: "{{ ptable | default(omit) }}"
        pxe_loader: "{{ pxe_loader | default(omit) }}"
        root_pass: "{{ root_pass | default(omit) }}"
        environment: "{{ puppet_environment | default(omit) }}"
        puppetclasses: "{{ puppetclasses | default(omit) }}"
        config_groups: "{{ config_groups | default(omit) }}"
        puppet_proxy: "{{ puppet_proxy | default(omit) }}"
        puppet_ca_proxy: "{{ puppet_ca_proxy | default(omit) }}"
        openscap_proxy: "{{ openscap_proxy | default(omit) }}"
        organization: "{{ organization | default(omit) }}"
        content_source: "{{ content_source | default(omit) }}"
        lifecycle_environment: "{{ lifecycle_environment | default(omit) }}"
        content_view: "{{ content_view | default(omit) }}"
        parameters: "{{ parameters | default(omit) }}"
        state: "{{ state }}"
      register: result

    - debug:
        var: result.entity.hostgroups[0].puppetclass_ids
      when: state == "present"

    - name: Get hostgroup info
      when: state == "present"
      resource_info:
        resource: hostgroups
        info: true
        search: "title = {{ parent + '/' + name if parent is defined else name }}"
      register: result

    - debug:
        var: result.resources[0].puppetclasses
      when: state == "present"

```

##### EXPECTED RESULTS
`puppetclasses` and/or `description` updated on same run

##### ACTUAL RESULTS

```
$ ansible-playbook playbook.yaml -e name=test -e puppetclasses=docker -e state=present
...
    "result.entity.hostgroups[0].puppetclass_ids": "VARIABLE IS NOT DEFINED!"
...
    "result.resources[0].puppetclasses": [
        {
            "id": 170,
            "module_name": "docker",
            "name": "docker"
        }
    ]

$ ansible-playbook playbook.yaml -e name=test -e puppetclasses=docker,hosts -e state=present
...
    "result.entity.hostgroups[0].puppetclass_ids": [
        170
    ]
...
    "result.resources[0].puppetclasses": [
        {
            "id": 170,
            "module_name": "docker",
            "name": "docker"
        }
    ]

$ ansible-playbook playbook.yaml -e name=test -e puppetclasses=docker,hosts -e state=absent
$ ansible-playbook playbook.yaml -e name=test -e puppetclasses=docker,hosts -e state=present
...
    "result.entity.hostgroups[0].puppetclass_ids": "VARIABLE IS NOT DEFINED!"
...
    "result.resources[0].puppetclasses": [
        {
            "id": 170,
            "module_name": "docker",
            "name": "docker"
        },
        {
            "id": 282,
            "module_name": "hosts",
            "name": "hosts"
        }
    ]

$ ansible-playbook playbook.yaml -e name=test -e puppetclasses=docker,hosts -e description=test -e state=present
...
fatal: [localhost]: FAILED! => {"changed": false, "error": {"message": "Validation failed: Puppet class has already been taken"}, "msg": "Error while performing create on hostgroup_classes: 500 Server Error: Internal Server Error for url: https://katello-url/api/hostgroups/11263/puppetclass_ids"}

$ ansible-playbook playbook.yaml -e name=test -e description=test -e state=present
ok: [localhost]
...
    "result.entity.hostgroups[0].puppetclass_ids": [
        170,
        282
    ]
...
    "result.resources[0].puppetclasses": [
        {
            "id": 170,
            "module_name": "docker",
            "name": "docker"
        },
        {
            "id": 282,
            "module_name": "hosts",
            "name": "hosts"
        }
    ]

```

**Comment by achevalet** [comment]
Note that we can update `description` in a separate task but it does not work for `puppetclasses`:
```yaml
---
- hosts: localhost
  collections:
    - theforeman.foreman
  gather_facts: false
  tasks:
    - name: Ensure Hostgroup '{{ name }}' is {{ state }}
      hostgroup:
        name: "{{ name }}"
        updated_name: "{{ updated_name | default(omit) }}"
        parent: "{{ parent | default(omit) }}"
        # description: "{{ description | default(omit) }}"
        locations: "{{ locations | default(omit) }}"
        organizations: "{{ organizations | default(omit) }}"
        compute_resource: "{{ compute_resource | default(omit) }}"
        compute_profile: "{{ compute_profile | default(omit) }}"
        domain: "{{ domain | default(omit) }}"
        subnet: "{{ subnet | default(omit) }}"
        subnet6: "{{ subnet6 | default(omit) }}"
        realm: "{{ realm | default(omit) }}"
        architecture: "{{ architecture | default(omit) }}"
        operatingsystem: "{{ operatingsystem | default(omit) }}"
        medium: "{{ installation_medium | default(omit) }}"
        ptable: "{{ ptable | default(omit) }}"
        pxe_loader: "{{ pxe_loader | default(omit) }}"
        root_pass: "{{ root_pass | default(omit) }}"
        environment: "{{ puppet_environment | default(omit) }}"
        puppetclasses: "{{ puppetclasses | default(omit) }}"
        config_groups: "{{ config_groups | default(omit) }}"
        puppet_proxy: "{{ puppet_proxy | default(omit) }}"
        puppet_ca_proxy: "{{ puppet_ca_proxy | default(omit) }}"
        openscap_proxy: "{{ openscap_proxy | default(omit) }}"
        organization: "{{ organization | default(omit) }}"
        content_source: "{{ content_source | default(omit) }}"
        lifecycle_environment: "{{ lifecycle_environment | default(omit) }}"
        content_view: "{{ content_view | default(omit) }}"
        parameters: "{{ parameters | default(omit) }}"
        state: "{{ state }}"
      register: result

    - name: Update description on Hostgroup '{{ name }}'
      when: state == "present"
      hostgroup:
        name: "{{ name }}"
        parent: "{{ parent | default(omit) }}"
        description: "{{ description | default(omit) }}"
        state: "{{ state }}"

    - name: Update puppetclasses on Hostgroup '{{ name }}'
      when: state == "present"
      hostgroup:
        name: "{{ name }}"
        parent: "{{ parent | default(omit) }}"
        puppetclasses: "{{ puppetclasses | default(omit) }}"
        state: "{{ state }}"

    - name: Get hostgroup info
      when: state == "present"
      resource_info:
        resource: hostgroups
        info: true
        search: "title = {{ parent + '/' + name if parent is defined else name }}"
      register: result

    - name: Show hostgroup details
      when: state == "present"
      debug:
        var: result.resources[0] | dict2items | rejectattr("value", "equalto", none) | list | items2dict
```
