### ISSUE TITLE
cluster value in vm_attr for compute profiles expect string

### ISSUE THREAD

**Issue by cmeissner** [theforeman/foreman-ansible-modules#1245]
##### SUMMARY

If we want to create compute profiles for vsphere compute resource the value of `cluster` within `vm_attrs` can't be an integer. We need to put an integer in quotes. 
As we can use numbers for cluster and or datacenter in Sphere configuration the module should also accept integers and may be do a type casting inside the module.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

ansible >= 2.9.0, <= 2.9.10

##### COLLECTION VERSION

theforeman.foreman:2.1.0

##### KATELLO/FOREMAN VERSION

foreman-server 2.1.4

##### STEPS TO REPRODUCE

This code should reproduce the issue.

```yaml
- name: setup compute profiles
  vars:
    compute_profile:
      name: "generic"
      compute_attributes:
        - compute_resource: "vsphere.example.com"
          vm_attrs:
            cpus: 1
            sockets: 1
            memory_mb: '2048'
            firmware: automatic
            cluster: 1337
            resource_pool: Resources
            path: "/Datacenters/1337/vm/1337_VM"
            guest_id: otherGuest64
            hardware_version: Default
            memoryHotAddEnabled: '0'
            cpuHotAddEnabled: '0'
            add_cdrom: '0'
            boot_order:
              - network
              - disk
            annotation: 'Foreman controlled vm'
            scsi_controllers:
              - type: VirtualLsiLogicController
                key: 1000
            interfaces_attributes:
              '0':
                type: VirtualE1000
                network: 1337_Service_PROD_1200
            volumes_attributes:
              '0':
                name: Hard disk
                thin: true
                mode: persistent
                controller_key: 1000
                size_gb: 10
                datastore: 1337_DS01
  theforeman.foreman.compute_profile:
    username: "{{ foreman_admin }}"
    password: "{{ foreman_admin_password }}"
    server_url: "https://foreman.example.com"
    validate_certs: "{{ validate_certs }}"
    name: "{{ compute_profile.name }}"
    compute_attributes: "{{ compute_profile.compute_attributes | default(omit) }}"
    state: "present"

```

##### EXPECTED RESULTS

Foreman should manage compute profile with a cluster name with integers only without complaining about.

##### ACTUAL RESULTS

```
TASK [config_foreman : Manage compute profile generic] **************************
70 fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find clusters '1894' on compute resource 'vcenter.example.com'."}
```
