### ISSUE TITLE
storage_pod can not be set

### ISSUE THREAD

**Issue by afeefghannam89** [theforeman/foreman-ansible-modules#1247]
##### SUMMARY
I am using compute_profile plugin to create configuration on katello. However, this plugin let the storage_pod parameter empty after problem free Ansible run

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.9.17
```

##### COLLECTION VERSION

```
v2.1.0
```

##### KATELLO/FOREMAN VERSION

```
tfm-rubygem-katello-3.16.0.20-1.el7sat.noarch
foreman-2.1.2.25-1.el7sat.noarch
```

##### STEPS TO REPRODUCE

```yaml
- name: Create compute profiles
  theforeman.foreman.compute_profile:
    name: "{{ item.name }}"
    compute_attributes: "{{ item.compute_attributes }}"
    server_url: "{{ satellite_url }}"
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ compute_profiles  | default([]) }}"
  when: compute_profiles is defined
  no_log: yes


###here is the host_vars:
compute_profiles:
  - name: Small
    compute_attributes:
    - compute_resource: ""
      vm_attrs:
        cluster: Cluster
        resource_pool: Resources
        cpus: 1
        corespersocket: 1
        memory_mb: 2048
        firmware: bios
        guest_id: rhel8_64Guest
        ha: 1
        scsi_controllers:
        - type: ParaVirtualSCSIController
        volumes_attributes:
          0:
            size_gb: 100
            thin: false
            mode: persistent
            storage_pod: VPLEX
        interfaces_attributes:
          0:
            type: VirtualVmxnet3
            network: VLAN51

............
```

##### EXPECTED RESULTS

Set the storage-pod parameter in my Small compute profile
##### ACTUAL RESULTS

```

```
