### ISSUE TITLE
parameters are getting overwritten

### ISSUE THREAD

**Issue by bhatsu** [theforeman/foreman-ansible-modules#1263]
##### SUMMARY
When we run a task to create multiple parameters by looping or by running two diff tasks only the last one is retained.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.9.15
```

##### COLLECTION VERSION

```

```

##### KATELLO/FOREMAN VERSION

```
tfm-rubygem-katello-4.1.0-1.el7.noarch
foreman-2.5.1-1.el7.noarch
```

##### STEPS TO REPRODUCE

Example #1
VARS:
```yaml
foreman_locations:
  - location: LOC1
    parameters:
      - name: 'dns1'
        value: '10.x.x.1'
      - name: 'dns2'
        value: '10.x.x.2'
      - name: 'dns_search_path'
        value: "['abc.com', 'def.com']"
        type: array
```
TASKS:
```yaml        
   - name: Create Foreman Locations
      theforeman.foreman.location:
        username: "{{ foreman_admin_user }}"
        password: "{{ foreman_admin_pass }}"
        server_url: "{{ foreman_url }}"
        validate_certs: False
        name: "{{ item.0.location }}"
        parameters:
          - name: "{{ item.1.name }}"
            parameter_type: "{{ item.1.type |default('string') }}"
            value: "{{ item.1.value }}"
        organizations: "{{ foreman_org }}"
        state: "present"
      with_subelements:
        - '{{ foreman_locations }}'
        - parameters
      tags:
        - foreman-config
        - foreman-locations
```
In this case only `dns_search_path` is retained.

Example #2
```yaml
   - name: Create Foreman Locations
      theforeman.foreman.location:
        username: "{{ foreman_admin_user }}"
        password: "{{ foreman_admin_pass }}"
        server_url: "{{ foreman_url }}"
        validate_certs: False
        name: "LOC1"
        parameters:
          - name: "var1"
            parameter_type: "string"
            value: "vaule1"
         - name: "var2"
            parameter_type: "string"
            value: "value2"
        organizations: "{{ foreman_org }}"
        state: "present"
       
    - name: Create Foreman Locations
      theforeman.foreman.location:
        username: "{{ foreman_admin_user }}"
        password: "{{ foreman_admin_pass }}"
        server_url: "{{ foreman_url }}"
        validate_certs: False
        name: "LOC1"
        parameters:
          - name: "var3"
            parameter_type: "string"
            value: "vaule3"
        organizations: "{{ foreman_org }}"
        state: "present"
```
And, in this case only `var3` is retained.

##### EXPECTED RESULTS

All values should be retained.
##### ACTUAL RESULTS
OUTPUT of play from Example #1
```yaml
TASK [Create Foreman Locations] ************************************************************************************************************************************************************************************************************
--- before
+++ after
@@ -9,12 +9,12 @@
         }
     ],
     "parameters": [
-        {},
         {
-            "id": 74,
-            "name": "dns2",
+            "id": 75,
+            "name": "dns1",
             "parameter_type": "string",
-            "value": "10.x.x.1"
-        }
+            "value": "10.x.x.2"
+        },
+        {}
     ]
 }

changed: [foreman.localhost] => (item=[{'location': 'LOC1'}, {'name': 'dns1', 'value': '10.x.x.2'}])
--- before
+++ after
@@ -9,12 +9,12 @@
         }
     ],
     "parameters": [
-        {},
         {
-            "id": 75,
-            "name": "dns1",
+            "id": 76,
+            "name": "dns2",
             "parameter_type": "string",
-            "value": "10.x.x.2"
-        }
+            "value": "10.x.x.1"
+        },
+        {}
     ]
 }

changed: [foreman.localhost] => (item=[{'location': 'LOC1'}, {'name': 'dns2', 'value': '10.x.x.1'}])
--- before
+++ after
@@ -9,12 +9,15 @@
         }
     ],
     "parameters": [
-        {},
         {
-            "id": 76,
-            "name": "dns2",
-            "parameter_type": "string",
-            "value": "10.x.x.1"
-        }
+            "id": 77,
+            "name": "dns_search_path",
+            "parameter_type": "array",
+            "value": [
+                "abc.com",
+                "def.com"
+            ]
+        },
+        {}
     ]
 }

changed: [foreman.localhost] => (item=[{'location': 'LOC1'}, {'name': 'dns_search_path', 'type': 'array', 'value': "['abc.com', 'def.com']"}])

```

OUTPUT of play from Example #2
```yaml
--- before
+++ after
@@ -9,13 +9,18 @@
         }
     ],
     "parameters": [
-        {},
-        {},
         {
-            "id": 67,
-            "name": "var3",
+            "id": 68,
+            "name": "var1",
             "parameter_type": "string",
-            "value": "value3"
-        }
+            "value": "value1"
+        },
+        {
+            "id": 69,
+            "name": "var2",
+            "parameter_type": "string",
+            "value": "value2"
+        },
+        {}
     ]
 }

changed: [foreman.localhost]

TASK [Create Foreman Locations] ************************************************************************************************************************************************************************************************************
--- before
+++ after
@@ -9,18 +9,13 @@
         }
     ],
     "parameters": [
+        {
+            "id": 70,
+            "name": "var3",
+            "parameter_type": "string",
+            "value": "value3"
+        },
         {},
-        {
-            "id": 68,
-            "name": "var1",
-            "parameter_type": "string",
-            "value": "value1"
-        },
-        {
-            "id": 69,
-            "name": "var2",
-            "parameter_type": "string",
-            "value": "value2"
-        }
+        {}
     ]
 }

changed: [foreman.localhost]


```
