### ISSUE TITLE
redhat_manifest module has no proxy parameters

### ISSUE THREAD

**Issue by tinsjourney** [theforeman/foreman-ansible-modules#1276]
##### SUMMARY

Using redhat_manifest module to download manifest directly from Red Hat Portal, with ansible host and satellite server behind corporate proxy server, but there is no proxy parameter we can give to module.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
(venv) [PROD] tins@localhost (~/gitlab/Ansible)$ ansible --version
ansible 2.8.18
  config file = /home/tins/gitlab/Ansible/ansible.cfg
  configured module search path = ['/home/tins/gitlab/Ansible']
  ansible python module location = /home/tins/venv/lib/python3.6/site-packages/ansible
  executable location = /home/tins/venv/bin/ansible
  python version = 3.6.12 (default, Sep 15 2020, 12:49:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-37)]
```

##### COLLECTION VERSION

```
redhat.satellite            2.1.2
redhat.satellite_operations 0.3.2
```

##### KATELLO/FOREMAN VERSION

```
tfm-rubygem-katello-3.18.1.33-1.el7sat.noarch
foreman-2.3.1.21-1.el7sat.noarch
```

##### STEPS TO REPRODUCE

```yaml
- name: Download Subscription Manifest from Red Hat Customer Portal
  redhat.satellite.redhat_manifest:
    uuid: "{{ satellite_manifest_uuid }}"
    username: "{{ satellite_rhsm_username }}"
    password: "{{ satellite_rhsm_password }}"
    path: "{{ satellite_manifest_path }}"
    validate_certs: False
```

##### EXPECTED RESULTS

Manifest downloaded from Red Hat Portal

##### ACTUAL RESULTS

ansible failed with error

```
No route to host: subscription.rhn.redhat.com
```

Settings proxy via envionment [1] fixed the issue 
```yaml
- name: Download Subscription Manifest from Red Hat Customer Portal
  redhat.satellite.redhat_manifest:
    uuid: "{{ satellite_manifest_uuid }}"
    username: "{{ satellite_rhsm_username }}"
    password: "{{ satellite_rhsm_password }}"
    path: "{{ satellite_manifest_path }}"
    validate_certs: False
  environment:
    https_proxy: http://proxy.local:8080/
```
I also tried with the role redhat.satellite.manifest, but the environment stuff didn't worked.

[1] https://docs.ansible.com/ansible/latest/user_guide/playbooks_environment.html#setting-the-remote-environment-in-a-task

**Comment by evgeni** [comment]
I think setting it via the environment is exactly the correct approach, it just needs to be properly documented.

Why it didn't work for you with the role is a different question.

**Comment by tinsjourney** [comment]
based on https://github.com/ansible/ansible/issues/39185, attributes applied to include_X only apply to the include itself, and are not inherited by the tasks within.

So in order to give proxy to role we need to use import_role.
I made it work using the following
```yaml
- host: localhost
  vars:
    proxy_env:
       http_proxy: http://192.168.122.1:3128/
       https_proxy: http://192.168.122.1:3128/
       no_proxy: satellite.redhat.local

  tasks:
    - name: "Install Subscription Manifest"
      import_role:
        name: redhat.satellite.manifest
      vars:
        satellite_manifest_path: "/tmp/manifest.zip"
        state: present
        satellite_manifest_download: True
        satellite_rhsm_username: "{{ vault_rhsm_username }}"
        satellite_rhsm_password: "{{ vault_rhsm_password }}"
        satellite_validate_certs: False
        satellite_manifest_uuid: "{{ vault_rhsm_manifestid }}"
      environment: "{{ proxy_env }}"
```
