### ISSUE TITLE
ERROR! couldn't resolve module/action 'theforeman.foreman.content_view_version_cleanup'. 

### ISSUE THREAD

**Issue by piellick** [theforeman/foreman-ansible-modules#1287]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.11.1] 
  config file = /local/git/awx-satellite/awx-satellite/ansible.cfg
  configured module search path = ['/home/XXXXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/XXXXXXX/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.6.8 (default, Mar 19 2021, 05:13:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.1
  libyaml = True
```

##### COLLECTION VERSION

```
# /home/XXXXXXX/.ansible/collections/ansible_collections
Collection            Version
--------------------- -------
servicenow.itsm       1.2.0  
servicenow.servicenow 1.0.6  
theforeman.foreman    2.2.0  
```

##### STEPS TO REPRODUCE

```


- hosts: localhost
  gather_facts: no
  tasks:

    - name: Include vars
      include_vars:
        dir: vars

     #this task works well
     - name: "FORCE PROMOTE and dowgrade version to 1.0 in TEST/DEV"
       theforeman.foreman.content_view_version:
         username: '{{ foreman_username }}'
         password: '{{ foreman_password }}'
         server_url: '{{ foreman_server_url }}'
         organization: '{{ foreman_org }}'
         content_view: "ANSIBLE_AUTO_TEST_RHEL7"
         version: "1.0"
         force_promote: yes
         lifecycle_environments:
           - TEST/DEV

    - name: "Remove content view 1.0"
      theforeman.foreman.content_view_version_cleanup:
        username: '{{ foreman_username }}'
        password: '{{ foreman_password }}'
        server_url: '{{ foreman_server_url }}'
        organization: '{{ foreman_org }}'
        content_view_version_cleanup_keep: 1
        content_view_version_cleanup_search: "name ~ some_content_view"

```

##### EXPECTED RESULTS

Try to call "theforeman.foreman.content_view_version_cleanup" in a task list like "theforeman.foreman.content_view"

##### ACTUAL RESULTS

```
ERROR! couldn't resolve module/action 'theforeman.foreman.content_view_version_cleanup'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/local/git/awx-satellite/awx-satellite/play.yml': line 89, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: "Remove content view 1.0"
      ^ here
```
