### ISSUE TITLE
Misleading documentation for theforeman.foreman.host when using host groups

### ISSUE THREAD

**Issue by sscheib-rh** [theforeman/foreman-ansible-modules#1298]
##### SUMMARY
The documentation regarding `theforeman.foreman.host` is misleading when using host groups.
The [documentation](https://docs.ansible.com/ansible/latest/collections/theforeman/foreman/host_module.html) mentions:
`hostgroup: Name of related hostgroup.`

Actually it should mention that the *title* has to be used. This is especially important, when working with subgroups.

Please see the following example:
parent host group: `foo`
sub host group of `foo`: `bar`
complete path therefore: `for/bar`

When using the module with `bar` only, it would reference any parent level host group, which has the name `bar`, but not the intended host group `foo/bar`. To achieve this, one has to use `foo/bar` as `hostgroup` parameter.

##### ISSUE TYPE
 - Bug Report

##### STEPS TO REPRODUCE

This playbook would create a host in a top level host group `bar` (if existent):
```yaml
- name: "Create a host"
  theforeman.foreman.host:
    username: "admin"
    password: "changeme"
    server_url: "https://foreman.example.com"
    name: "new_host"
    hostgroup: bar
    state: present
```

To reference the sub group one has to do it like so:
```yaml
- name: "Create a host"
  theforeman.foreman.host:
    username: "admin"
    password: "changeme"
    server_url: "https://foreman.example.com"
    name: "new_host"
    hostgroup: 'foo/bar'
    state: present
```

##### EXPECTED RESULTS
The documentation should mention the use of 'title' instead of 'name'
