### ISSUE TITLE
Remove of nested hostgroups not idempotent

### ISSUE THREAD

**Issue by SimonLorentz** [theforeman/foreman-ansible-modules#1301]
##### SUMMARY
When I delete nested hostgroups via Ansible I get an error: 

Found no results while searching for hostgroups with title="child"

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.25
```

##### COLLECTION VERSION

```
theforeman.foreman 2.2.0
```

##### KATELLO/FOREMAN VERSION

```
tfm-rubygem-katello-3.18.1.37-1.el7sat.noarch
foreman-2.3.1.23-1.el7sat.noarch
```

##### STEPS TO REPRODUCE

```yaml
---                                                                                                     
- hosts: localhost 
  connection: local
  module_defaults: 
    theforeman.foreman.hostgroup: 
      username: "usr"                                                                            
      password: "psw" 
      server_url: "url" 
      validate_certs: "false"                                                                                                     
  tasks: 
    - name: "Remove hostgroups"                                                  
      theforeman.foreman.hostgroup:                                              
        name: "{{ item.name }}"                                                  
        parent: "{{ item.parent | default(omit) }}"                              
        organization: "{{ item.organization }}"                                 
        locations: "{{ item.locations }}"                                                                
        state: absent
      loop:                                                                      
        - name: "parent"                                                
          organization: "myorg"                                            
          locations: "mylocation"                                                
        - name: "child"                                                     
          parent: "parent"                                              
          organization: "myorg"                                            
          locations: "mylocation"
```

##### EXPECTED RESULTS

First run will throw an error, that parent can´t be deleted, because of nested group, thats okay, but in the second run I get an error, that he can´t find the child. I would expect in the second run, that i get a changed on the parent hostgroup and an ok for the child and not an error

##### ACTUAL RESULTS

```
First run will throw an error, that parent can´t be deleted, because of nested group, thats okay, but in the second run I get an error, that he can´t find the child.
```

**Comment by mdellweg** [comment]
That is surprising to me, as we have a idempotence tests for nested hostgroup deletion (using both syntax).

https://github.com/theforeman/foreman-ansible-modules/blob/develop/tests/test_playbooks/hostgroup.yml#L490
https://github.com/theforeman/foreman-ansible-modules/blob/develop/tests/test_playbooks/hostgroup.yml#L514

Can you verify, the parent host group still exists after the first run?

**Comment by SimonLorentz** [comment]
Yes after the first run the child is deleted and the parent still exists, in the second run the parent is deleted and i get an error for the child. In the third run I get an ok for the parent and still an error for the child.

**Comment by evgeni** [comment]
what's the behaviour if you change the loop to:

```yaml
      loop:                                                                      
        - name: "child"                                                     
          parent: "parent"                                              
          organization: "myorg"                                            
          locations: "mylocation"
        - name: "parent"                                                
          organization: "myorg"                                            
          locations: "mylocation"                                                
```

So it *first* try to delete the child, and only *then* tries to delete the parent?
