### ISSUE TITLE
Product name ended by ")" not supported

### ISSUE THREAD

**Issue by dur3x** [theforeman/foreman-ansible-modules#132]
```
 katello_sync:
      username: "user"
      password: "password"
      server_url: "https://example.org"
      verify_ssl: false
      organization: "TestOrg"
      product: "Extra Packages for Enterprise Linux (EPEL)"
      repository: "test"
```

> fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html\n  InsecureRequestWarning)\n/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html\n  InsecureRequestWarning)\n/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_ABkOdm/ansible_module_katello_sync.py\", line 189, in <module>\n    main()\n  File \"/tmp/ansible_ABkOdm/ansible_module_katello_sync.py\", line 185, in main\n    module.fail_json(msg=e)\n  File \"/tmp/ansible_ABkOdm/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2378, in fail_json\n  File \"/tmp/ansible_ABkOdm/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2355, in _return_formatted\n  File \"/tmp/ansible_ABkOdm/ansible_modlib.zip/ansible/module_utils/basic.py\", line 524, in remove_values\n  File \"/tmp/ansible_ABkOdm/ansible_modlib.zip/ansible/module_utils/basic.py\", line 507, in _remove_values_conditions\nTypeError: Value of unknown type: <type 'exceptions.TypeError'>, A value must be provided for the \"organization\" field.\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

If I rename "Extra Packages for Enterprise Linux (EPEL)" by something like "Toto Tata" it works but it will be better if we can well support the initial name.
