### ISSUE TITLE
Smart class parameters add matcher always overrides existing matchers

### ISSUE THREAD

**Issue by mannyci** [theforeman/foreman-ansible-modules#1355]
##### SUMMARY
Puppet smart class params always overrides existing params for a smart class parameter. It removes all previous matchers and replaces with the new one

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible [core 2.12.1]
```

##### COLLECTION VERSION

```
theforeman.foreman 3.1.0
```

##### KATELLO/FOREMAN VERSION
```
3.18.15.0
```

##### STEPS TO REPRODUCE
```yaml
  - name: Add Smart Class parameter matcher
    theforeman.foreman.smart_class_parameter:
      server_url: "{{ satellite_server_url | default(omit) }}"
      username: "{{ satellite_username | default(omit) }}"
      password: "{{ satellite_password | default(omit) }}"
      validate_certs: "{{ satellite_validate_certs | default(omit) }}"
      puppetclass_name: "puppet_class"
      parameter: "sc_param_name"
      override_values:
        - value: "bla"
          match: "fqdn=host_fqdn.com"
```

##### EXPECTED RESULTS
Add this matcher to the sc-param matchers list

##### ACTUAL RESULTS
This matcher replaces all existing matchers and replaces only this one
