### ISSUE TITLE
Sugestion for a better way to handle multiple organizations in Katello roles

### ISSUE THREAD

**Issue by reenberg** [theforeman/foreman-ansible-modules#1362]
##### SUMMARY
I'm working with multiple organizations in my Foreman Katello setup, and its really bad to use the supplied Katello roles (for example the `theforeman.foreman.lifecycle_environments`).  It almost works directly against you by having hardcoded the  organizations to be the `foreman_organization` variable.

My current fix is to have the Foreman roles  under the roles section of my playbook, and then add all Katello roles under the tasks section, as I can then do nasty stuff like this:

```
 role: 
    - theforeman.foreman.organizations

 tasks:
    # Katello configurations can't take a list or organizations.
    - include_role:
        name: theforeman.foreman.lifecycle_environments
      loop_control:
        loop_var: foreman_organization
      with_items: "{{ foreman_organizations | map(attribute='name') | list }}"
```

However this still feels quite ugly.

##### ISSUE TYPE

Inspired by my initial fix, I went ahead and added a new `katello_organizations` filter, which can be used in the helper roles.

filer:

```python
def katello_organizations(values):
    """Flattens the Foreman organizations attribute into a list of Katello
    compatible organization attributes.

    Expects a list of Katello resources as input, if they have an
    `organizations` attribute, then the resource is turned into a list of the
    same resource, but with the `organization` attribute set for each element of
    the original `organizations` attribute.

    If both `organization` and `organizations` are defined directly in the
    object, then `organizations` will overwrite.

    Attributes
    ----------
    values : list[dict[]]
        List of katello resources

    Returns
    -------
    list[dict[]]
        a list of Katello resources
    """
    if not isinstance(values, list):
        raise AnsibleFilterError(
            "Argument for theforeman.foreman.katello_organizations must be a "
            "list of katello resources. %s is %s" % (values, type(values)))

    res = []
    for elem in values:
        if 'organizations' in elem:
            # Make a deep copy of the dict, to ensure any other filter
            # operations later on may not have suprising behaviour.
            elem_ = elem.copy()
            del elem_['organizations']

            for org in elem['organizations']:
                elem_org = elem_.copy()
                elem_org.update(organization=org)
                res.append(elem_org)
        else:
            res.append(elem)
    return res
```
I guess one could do some more type instance handling to be a bit more "user friendly".  And also create a single element list, if the `organizations` attribute was a string.

Then the lifecycle environment role can be update to the following.  Note how the organizations attribute is updated, and still uses the `foreman_organization` as a default value if the `item.organization` isn't defined originally or by the filter.  This was an attempt at being backwards compatible.

```yaml
---
- name: 'Create Lifecycle Environments'
  theforeman.foreman.lifecycle_environment:
    username: "{{ foreman_username | default(omit) }}"
    password: "{{ foreman_password | default(omit) }}"
    server_url: "{{ foreman_server_url | default(omit) }}"
    validate_certs: "{{ foreman_validate_certs | default(omit) }}"
    organization: "{{ item.organization | default(foreman_organization) }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    prior: "{{ item.prior }}"
    label: "{{ item.label | default(omit) }}"
    state: present
  with_items:
    # XXX: Perhaps the default foreman_organization logic could be added to the
    # katello_organizations filter.
    - "{{ foreman_lifecycle_environments | theforeman.foreman.katello_organizations }}"
```

This actually also allows the `foreman_lifecycle_environments` variable definition to also define the `organization` attribute directly if just one is needed.  
Obviously a bit of README needs updating, and the other roles needs "fixed" as well.

Is this concept something that is usable, or?  If so, then I guess I will make a PR with the katello roles fixed.

Any direct reason why the state is hardcoded to `present` for this role?  It kind of seems, that the Katello roles haven't gotten that much love as of yet?
