### ISSUE TITLE
theforeman.foreman.content_view_filter unable to create rules

### ISSUE THREAD

**Issue by Siddhu1096** [theforeman/foreman-ansible-modules#1372]
##### SUMMARY

theforeman.foreman.content_view_filter is unable to create rules. It says the 3 other packages with the same name found even though we have specified the correct content view and product name. Raising the issue here as directed from community portal of foreman. For reference - https://community.theforeman.org/t/how-to-give-repositories-input-in-content-view-filter/27993/5?u=almond

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.27
```

##### COLLECTION VERSION

```

```

##### KATELLO/FOREMAN VERSION

```
foreman-3.1.0-1.el8.noarch
```

##### STEPS TO REPRODUCE

Run the below yaml file after creating multiple products and their content views

```
  - name: my_filter
    theforeman.foreman.content_view_filter:
      username: "admin"
      password: "admin"
      server_url: "myhost"
      name: "package filter 1"
      organization: "COT"
      content_view: "Test_Alma84"
      filter_type: "package_group"
      rule_name: "Core"
      repositories:
        - name: BaseOS
          product: Almatest_84

```

##### EXPECTED RESULTS

The expected results is to create filter "package_filter_1" and add "Core" as package_filter rule
##### ACTUAL RESULTS

But in our case we are getting an error saying 4 more results are found in the same name even after adding content view and product name. 

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Found too many (4) results while searching for package_groups with name=\"Core\""}
```
