### ISSUE TITLE
activation_key module keeps updating content_overrides

### ISSUE THREAD

**Issue by gvde** [theforeman/foreman-ansible-modules#1400]
##### SUMMARY
Running against a katello 4.3 or 4.4 server my playbook always wants to change the content_overrides or my activation keys.

```
TASK [theforeman.foreman.activation_keys : Create Activation Keys] ***************************************************************************************************************************************************************************
--- before
+++ after
@@ -14,7 +14,22 @@
     ],
     "activation_keys/content_overrides": [
         {
-            "content_overrides": {},
+            "content_overrides": {
+                "ORG_centos7_centosplus_x86_64": false,
+                "ORG_centos7_extras_x86_64": false,
+                "ORG_centos7_sclo_x86_64_rh": false,
+                "ORG_centos7_sclo_x86_64_sclo": false,
+                "ORG_dkrz_el8": false,
+                "ORG_foreman-client_3_0_el7_x86_64": false,
+                "ORG_foreman-client_3_0_el8_x86_64": false,
+                "ORG_foreman-client_3_1_el8_x86_64": false,
+                "ORG_foreman-client_3_2_el7_x86_64": false,
+                "ORG_foreman-client_3_2_el8_x86_64": false,
+                "ORG_puppet_puppet6_buster": false,
+                "ORG_puppet_puppet6_el8_x86_64": false,
+                "ORG_puppet_puppet7_el7_x86_64": false,
+                "ORG_puppet_puppet7_el8_x86_64": false
+            },
             "id": 2
         }
     ]

changed: [foreman8.example.com] => (item={'name': 'Standard CentOS 7 Server', 'lifecycle_environment': 'Production', 'content_view': 'CentOS 7', 'subscriptions': [{'name': 'CentOS 7'}, {'name': 'ORG'}, {'name': 'EPEL 7'}, {'name': 'Foreman Client'}, {'name': 'Puppet'}], 'content_overrides': [{'label': 'ORG_centos7_extras_x86_64', 'override': 'disabled'}, {'label': 'ORG_centos7_centosplus_x86_64', 'override': 'disabled'}, {'label': 'ORG_centos7_sclo_x86_64_rh', 'override': 'disabled'}, {'label': 'ORG_centos7_sclo_x86_64_sclo', 'override': 'disabled'}, {'label': 'ORG_dkrz_el8', 'override': 'disabled'}, {'label': 'ORG_foreman-client_3_0_el7_x86_64', 'override': 'disabled'}, {'label': 'ORG_foreman-client_3_0_el8_x86_64', 'override': 'disabled'}, {'label': 'ORG_foreman-client_3_1_el8_x86_64', 'override': 'disabled'}, {'label': 'ORG_foreman-client_3_2_el7_x86_64', 'override': 'disabled'}, {'label': 'ORG_foreman-client_3_2_el8_x86_64', 'override': 'disabled'}, {'label': 'ORG_puppet_puppet6_buster', 'override': 'disabled'}, {'label': 'ORG_puppet_puppet6_el8_x86_64', 'override': 'disabled'}, {'label': 'ORG_puppet_puppet7_el7_x86_64', 'override': 'disabled'}, {'label': 'ORG_puppet_puppet7_el8_x86_64', 'override': 'disabled'}]})
--- before
+++ after
@@ -15,7 +15,17 @@
     "activation_keys/content_overrides": [
         {
             "content_overrides": {
-                "ORG_almalinux8_HighAvailability_x86_64_os": false
+                "ORG_almalinux8_HighAvailability_x86_64_os": false,
+                "ORG_dkrz_el7": false,
+                "ORG_foreman-client_3_0_el7_x86_64": false,
+                "ORG_foreman-client_3_0_el8_x86_64": false,
+                "ORG_foreman-client_3_1_el7_x86_64": false,
+                "ORG_foreman-client_3_2_el7_x86_64": false,
+                "ORG_foreman-client_3_2_el8_x86_64": false,
+                "ORG_puppet_puppet6_buster": false,
+                "ORG_puppet_puppet6_el7_x86_64": false,
+                "ORG_puppet_puppet7_el7_x86_64": false,
+                "ORG_puppet_puppet7_el8_x86_64": false
             },
             "id": 5
         }

changed: [foreman8.example.com] => (item={'name': 'Standard AlmaLinux 8 Server', 'lifecycle_environment': 'Production', 'content_view': 'EL 8', 'subscriptions': [{'name': 'AlmaLinux 8'}, {'name': 'ORG'}, {'name': 'EPEL 8'}, {'name': 'Foreman Client'}, {'name': 'Puppet'}], 'content_overrides': [{'label': 'ORG_almalinux8_HighAvailability_x86_64_os', 'override': 'disabled'}, {'label': 'ORG_dkrz_el7', 'override': 'disabled'}, {'label': 'ORG_foreman-client_3_0_el7_x86_64', 'override': 'disabled'}, {'label': 'ORG_foreman-client_3_0_el8_x86_64', 'override': 'disabled'}, {'label': 'ORG_foreman-client_3_1_el7_x86_64', 'override': 'disabled'}, {'label': 'ORG_foreman-client_3_2_el7_x86_64', 'override': 'disabled'}, {'label': 'ORG_foreman-client_3_2_el8_x86_64', 'override': 'disabled'}, {'label': 'ORG_puppet_puppet6_buster', 'override': 'disabled'}, {'label': 'ORG_puppet_puppet6_el7_x86_64', 'override': 'disabled'}, {'label': 'ORG_puppet_puppet7_el7_x86_64', 'override': 'disabled'}, {'label': 'ORG_puppet_puppet7_el8_x86_64', 'override': 'disabled'}]})
--- before
+++ after
@@ -14,7 +14,20 @@
     ],
     "activation_keys/content_overrides": [
         {
-            "content_overrides": {},
+            "content_overrides": {
+                "ORG_centos8stream_HighAvailability_x86_64_os": false,
+                "ORG_centos8stream_centosplus_x86_64_os": false,
+                "ORG_dkrz_el7": false,
+                "ORG_foreman-client_3_0_el7_x86_64": false,
+                "ORG_foreman-client_3_0_el8_x86_64": false,
+                "ORG_foreman-client_3_1_el7_x86_64": false,
+                "ORG_foreman-client_3_2_el7_x86_64": false,
+                "ORG_foreman-client_3_2_el8_x86_64": false,
+                "ORG_puppet_puppet6_buster": false,
+                "ORG_puppet_puppet6_el7_x86_64": false,
+                "ORG_puppet_puppet7_el7_x86_64": false,
+                "ORG_puppet_puppet7_el8_x86_64": false
+            },
             "id": 6
         }
     ]

changed: [foreman8.example.com] => (item={'name': 'Standard CentOS 8 Stream Server', 'lifecycle_environment': 'Production', 'content_view': 'EL 8', 'subscriptions': [{'name': 'CentOS 8 Stream'}, {'name': 'ORG'}, {'name': 'EPEL 8'}, {'name': 'Foreman Client'}, {'name': 'Puppet'}], 'content_overrides': [{'label': 'ORG_centos8stream_HighAvailability_x86_64_os', 'override': 'disabled'}, {'label': 'ORG_centos8stream_centosplus_x86_64_os', 'override': 'disabled'}, {'label': 'ORG_dkrz_el7', 'override': 'disabled'}, {'label': 'ORG_foreman-client_3_0_el7_x86_64', 'override': 'disabled'}, {'label': 'ORG_foreman-client_3_0_el8_x86_64', 'override': 'disabled'}, {'label': 'ORG_foreman-client_3_1_el7_x86_64', 'override': 'disabled'}, {'label': 'ORG_foreman-client_3_2_el7_x86_64', 'override': 'disabled'}, {'label': 'ORG_foreman-client_3_2_el8_x86_64', 'override': 'disabled'}, {'label': 'ORG_puppet_puppet6_buster', 'override': 'disabled'}, {'label': 'ORG_puppet_puppet6_el7_x86_64', 'override': 'disabled'}, {'label': 'ORG_puppet_puppet7_el7_x86_64', 'override': 'disabled'}, {'label': 'ORG_puppet_puppet7_el8_x86_64', 'override': 'disabled'}]})
```

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.9.27
  config file = /home/k/k111111/git/foreman-ansible/ansible.cfg
  configured module search path = ['/home/k/k111111/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Nov 17 2021, 16:10:06) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
```

##### COLLECTION VERSION
Using latest version 3.3.0 from ansible-galaxy with some patches from pull requests.

##### KATELLO/FOREMAN VERSION

```
katello-4.4.0-1.el8.noarch
foreman-3.2.0-1.el8.noarch
```

##### STEPS TO REPRODUCE
```
    - role: theforeman.foreman.activation_keys
      vars:
        foreman_activation_keys:
          - name: "Standard CentOS 7 Server"
            lifecycle_environment: "Production"
            content_view: "CentOS 7"
            subscriptions:
              - name: "CentOS 7"
              - name: "ORG"
              - name: "EPEL 7"
              - name: "Foreman Client"
              - name: "Puppet"
            content_overrides:
              - label: "ORG_centos7_extras_x86_64"
                override: disabled
              - label: "ORG_centos7_centosplus_x86_64"
                override: disabled
              - label: "ORG_centos7_sclo_x86_64_rh"
                override: disabled
              - label: "ORG_centos7_sclo_x86_64_sclo"
                override: disabled
              - label: "ORG_dkrz_el8"
                override: disabled
              - label: "ORG_foreman-client_3_0_el7_x86_64"
                override: disabled
              - label: "ORG_foreman-client_3_0_el8_x86_64"
                override: disabled
              - label: "ORG_foreman-client_3_1_el8_x86_64"
                override: disabled
              - label: "ORG_foreman-client_3_2_el7_x86_64"
                override: disabled
              - label: "ORG_foreman-client_3_2_el8_x86_64"
                override: disabled
              - label: "ORG_puppet_puppet6_buster"
                override: disabled
              - label: "ORG_puppet_puppet6_el8_x86_64"
                override: disabled
              - label: "ORG_puppet_puppet7_el7_x86_64"
                override: disabled
              - label: "ORG_puppet_puppet7_el8_x86_64"
                override: disabled
          - name: "Standard AlmaLinux 8 Server"
            lifecycle_environment: "Production"
            content_view: "EL 8"
            subscriptions:
              - name: "AlmaLinux 8"
              - name: "ORG"
              - name: "EPEL 8"
              - name: "Foreman Client"
              - name: "Puppet"
            content_overrides:
              - label: "ORG_almalinux8_HighAvailability_x86_64_os"
                override: disabled
              - label: "ORG_dkrz_el7"
                override: disabled
              - label: "ORG_foreman-client_3_0_el7_x86_64"
                override: disabled
              - label: "ORG_foreman-client_3_0_el8_x86_64"
                override: disabled
              - label: "ORG_foreman-client_3_1_el7_x86_64"
                override: disabled
              - label: "ORG_foreman-client_3_2_el7_x86_64"
                override: disabled
              - label: "ORG_foreman-client_3_2_el8_x86_64"
                override: disabled
              - label: "ORG_puppet_puppet6_buster"
                override: disabled
              - label: "ORG_puppet_puppet6_el7_x86_64"
                override: disabled
              - label: "ORG_puppet_puppet7_el7_x86_64"
                override: disabled
              - label: "ORG_puppet_puppet7_el8_x86_64"
                override: disabled
          - name: "Standard CentOS 8 Stream Server"
            lifecycle_environment: "Production"
            content_view: "EL 8"
            subscriptions:
              - name: "CentOS 8 Stream"
              - name: "ORG"
              - name: "EPEL 8"
              - name: "Foreman Client"
              - name: "Puppet"
            content_overrides:
              - label: "ORG_centos8stream_HighAvailability_x86_64_os"
                override: disabled
              - label: "ORG_centos8stream_centosplus_x86_64_os"
                override: disabled
              - label: "ORG_dkrz_el7"
                override: disabled
              - label: "ORG_foreman-client_3_0_el7_x86_64"
                override: disabled
              - label: "ORG_foreman-client_3_0_el8_x86_64"
                override: disabled
              - label: "ORG_foreman-client_3_1_el7_x86_64"
                override: disabled
              - label: "ORG_foreman-client_3_2_el7_x86_64"
                override: disabled
              - label: "ORG_foreman-client_3_2_el8_x86_64"
                override: disabled
              - label: "ORG_puppet_puppet6_buster"
                override: disabled
              - label: "ORG_puppet_puppet6_el7_x86_64"
                override: disabled
              - label: "ORG_puppet_puppet7_el7_x86_64"
                override: disabled
              - label: "ORG_puppet_puppet7_el8_x86_64"
                override: disabled
```

##### EXPECTED RESULTS
Don't suggest any changes during the second run.
