### ISSUE TITLE
operatingsystems ambiguity 

### ISSUE THREAD

**Issue by gvde** [theforeman/foreman-ansible-modules#1401]
##### SUMMARY
Running against a katello 4.3 or 4.4 server my playbook complains about the operating systems to be created/updated:

```
[WARNING]: While constructing a mapping from /home/k/k202081/git/foreman-ansible/first.yaml, line 1834, column 9, found a duplicate dict key (foreman_operatingsystems). Using
last defined value only.
```

It seems the problem is that multiple operating systems can have the same name, e.g. AlmaLinux. I have AlmaLinux with major version 8 and no minor version (AlmaLinux 8) and one with minor version 5 (AlmaLinux 8.5)

When adding and syncing AlmaLinux repositories it automatically generates a distribution and operating system "AlmaLinux 8".

The a client host with AlmaLinux 8.5 is registered it automatically generates an operating system "AlmaLinux 8.5" (from puppet facts or subscription manager?)

So this scenario seems standard.

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.9.27
  config file = /home/k/k111111/git/foreman-ansible/ansible.cfg
  configured module search path = ['/home/k/k111111/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Nov 17 2021, 16:10:06) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
```

##### COLLECTION VERSION
Using latest version 3.3.0 from ansible-galaxy with some patches from pull requests.

##### KATELLO/FOREMAN VERSION

```
katello-4.4.0-1.el8.noarch
foreman-3.2.0-1.el8.noarch
```

##### STEPS TO REPRODUCE
Playbook

```
    - role: theforeman.foreman.operatingsystems
      vars:
        foreman_operatingsystems:
          - name: "AlmaLinux"
            major: "8"
            description: "AlmaLinux 8"
            os_family: "Redhat"
            architectures:
              - "x86_64"
            password_hash: "SHA256"
            media:
              - "AlmaLinux 8"
              - "Local AlmaLinux 8"
        foreman_operatingsystems:
          - name: "AlmaLinux"
            major: "8"
            minor: "5"
            description: "AlmaLinux 8.5"
            os_family: "Redhat"
            architectures:
              - "x86_64"
            password_hash: "SHA256"
            media:
              - "AlmaLinux 8"
              - "Local AlmaLinux 8"
           override: disabled
```

##### EXPECTED RESULTS
No error and correct configuration of all operating system entities.

**Comment by evgeni** [comment]
I think your yaml is wrong.

Shouldn't it be

```yaml
    - role: theforeman.foreman.operatingsystems
      vars:
        foreman_operatingsystems:
          - name: "AlmaLinux"
            major: "8"
            description: "AlmaLinux 8"
            os_family: "Redhat"
            architectures:
              - "x86_64"
            password_hash: "SHA256"
            media:
              - "AlmaLinux 8"
              - "Local AlmaLinux 8"
          - name: "AlmaLinux"
            major: "8"
            minor: "5"
            description: "AlmaLinux 8.5"
            os_family: "Redhat"
            architectures:
              - "x86_64"
            password_hash: "SHA256"
            media:
              - "AlmaLinux 8"
              - "Local AlmaLinux 8"
```
