### ISSUE TITLE
external_usergroup does not support multiple auth sources.

### ISSUE THREAD

**Issue by gvde** [theforeman/foreman-ansible-modules#1422]
##### SUMMARY
theforeman.foreman.external_usergroup in 3.4.0 does not allow to set multiple authentication sources to link a user group to multiple sources, e.g. to External and an LDAP.

See apidoc 

https://apidocs.theforeman.org/katello/latest/apidoc/v2/external_usergroups/index.html

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/k/k111111/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/k/k111111/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Apr 21 2022, 07:55:08) [GCC 8.5.0 20210514 (Red Hat 8.5.0-10)]
  jinja version = 3.0.2
  libyaml = False
```

##### COLLECTION VERSION

```
$ ansible-galaxy collection list

# /usr/share/ansible/collections/ansible_collections
Collection         Version
------------------ -------
redhat.rhel_mgmt   1.0.0  
theforeman.foreman 3.1.0  

# /home/k/k111111/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
theforeman.foreman 3.4.0  

```

##### KATELLO/FOREMAN VERSION

```
$ rpm -q tfm-rubygem-katello foreman
package tfm-rubygem-katello is not installed
foreman-3.2.1-1.el8.noarch
```

##### STEPS TO REPRODUCE

```yaml
    - name: Create external group system on ldap
      theforeman.foreman.external_usergroup:
        username: "{{ foreman_username | default(omit) }}"
        password: "{{ foreman_password | default(omit) }}"
        server_url: "{{ foreman_server_url | default(omit) }}"
        name: system
        auth_source: "idm.example.com"
        usergroup: "system"
        state: present
    - name: Create external group system
      theforeman.foreman.external_usergroup:
        username: "{{ foreman_username | default(omit) }}"
        password: "{{ foreman_password | default(omit) }}"
        server_url: "{{ foreman_server_url | default(omit) }}"
        name: system
        auth_source: "External"
        usergroup: "system"
        state: present
```

##### EXPECTED RESULTS

auth_source should be an array, allowing multiple auth sources.

##### ACTUAL RESULTS

The playbook replaces the previous auth source or fails if the usergroup has two auth sources assigned.
