### ISSUE TITLE
theforeman.foreman.smart_class_parameter handling of hidden_value

### ISSUE THREAD

**Issue by gvde** [theforeman/foreman-ansible-modules#1426]
##### SUMMARY
theforeman.foreman.smart_class_parameter in 3.4.0 always wants to remove the hidden_value parameter.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/k/k111111/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/k/k111111/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Apr 21 2022, 07:55:08) [GCC 8.5.0 20210514 (Red Hat 8.5.0-10)]
  jinja version = 3.0.2
  libyaml = False
```

##### COLLECTION VERSION

```
$ ansible-galaxy collection list

# /usr/share/ansible/collections/ansible_collections
Collection         Version
------------------ -------
redhat.rhel_mgmt   1.0.0  
theforeman.foreman 3.1.0  

# /home/k/k111111/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
theforeman.foreman 3.4.0  

```

##### KATELLO/FOREMAN VERSION

```
$ rpm -q katello foreman
katello-4.4.1-1.el8.noarch
foreman-3.2.1-1.el8.noarch
```

##### STEPS TO REPRODUCE

```yaml
    - name: "Override org_ipa::access"
      theforeman.foreman.smart_class_parameter:
        username: "{{ foreman_username | default(omit) }}"
        password: "{{ foreman_password | default(omit) }}"
        server_url: "{{ foreman_server_url | default(omit) }}"
        puppetclass_name: "org_ipa"
        parameter: "access"
        override: true
        default_value: []
        override_values:
          - match: fqdn=foreman8.example.com
            value: ["+ : foreman : cron crond"]
```

##### EXPECTED RESULTS

It shouldn't show hidden_value in diff each run.

##### ACTUAL RESULTS

It looks like this on every run (after the first one of course):

```
TASK [Override org_ipa::access] ***********************************************************************************************************************************************************
--- before
+++ after
@@ -11,7 +11,6 @@
         {
             "avoid_duplicates": false,
             "default_value": "[]",
-            "hidden_value": false,
             "id": 104,
             "merge_default": false,
             "merge_overrides": false,

changed: [foreman8.example.com]
```
