### ISSUE TITLE
Add state present_with_defaults to host and hostgroup module

### ISSUE THREAD

**Issue by milanzelenka** [theforeman/foreman-ansible-modules#1442]
##### SUMMARY
Adding **`state: present_with_defaults`** to host (and hostgroups) module helps to idempotency in playbook with build: true.

```
theforeman.foreman.host:
  name: XY
  state: present
  build: true
```
=> existing installed XY host will be switched into build mode again (and re-builded depending on provision_method)

```
theforeman.foreman.host:
  name: XY
  state: present_with_defaults
  build: true
```
=> no change on existing installed XY host

##### ISSUE TYPE
 - Feature Idea
