### ISSUE TITLE
Operatingsystems role is not idempotent

### ISSUE THREAD

**Issue by Greek-Fire** [theforeman/foreman-ansible-modules#1459]
##### SUMMARY
The role will fail if I attempt to remove a template from the operating system, using the operatingsystems role.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.13.3]
  config file = None
  configured module search path = ['/Users/greek_fire/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/greek_fire/.ansible/collections:/usr/share/ansible/collections
  executable location = /Library/Frameworks/Python.framework/Versions/3.10/bin/ansible
  python version = 3.10.1 (v3.10.1:2cd268a3a9, Dec  6 2021, 14:28:59) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
Collection          Version
------------------- -------
ansible.posix       1.4.0  
installer.kickstart 1.0.0  
theforeman.foreman  3.4.0  
```

##### KATELLO/FOREMAN VERSION

```
package tfm-rubygem-katello is not installed
foreman-3.1.1.21-2.el8sat.noarch
```
##### STEPS TO REPRODUCE

```
foreman_operatingsystems:
- name:  "RedHat"
  major: "8"
  minor: "6"
  os_family: "Redhat"
  password_hash: "SHA256"
  architectures: "x86_64"
  description:   "KS RHEL 8.6"
  default_templates:
  - template_kind: "provision"
    provisioning_template: "Kickstart default"
  - template_kind: "PXELinux"
    provisioning_template: "Kickstart default PXELinux"
  - template_kind: "iPXE"
    provisioning_template: "Kickstart default iPXE"
  - template_kind: "PXEGrub"
    provisioning_template: "Kickstart default PXEGrub"
  - template_kind: "PXEGrub2"
    provisioning_template: "Kickstart default PXEGrub2"
  - template_kind: "finish"
    provisioning_template: "Kickstart default finish"
  - template_kind: "user_data"
    state: absent
```
##### EXPECTED RESULTS

```
changed: [sat] => (item=[{'name': 'RedHat', 'major': '8', 'minor': '6', 'os_family': 'Redhat','password_hash': 'SHA256', 'architectures': 'x86_64', 'description': 'KS RHEL 8.6','default_templates': 
[{'template_kind': 'provision', 'provisioning_template': 'Kickstart default'},
{'template_kind': 'PXELinux', 'provisioning_template': 'Kickstart default PXELinux'},
{'template_kind': 'iPXE', 'provisioning_template': 'Kickstart default iPXE'}, 
{'template_kind': 'PXEGrub', 'provisioning_template': 'Kickstart default PXEGrub'}, 
{'template_kind': 'PXEGrub2', 'provisioning_template': 'Kickstart default PXEGrub2'},
{'template_kind': 'finish', 'provisioning_template': 'Kickstart default finish'}, 
{'template_kind': 'user_data', 'state': 'absent'}]}, 
{'template_kind': 'user_data', 'state': 'absent'}])
```
##### ACTUAL RESULTS

```
fatal: [sat]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'provisioning_template'\n\nThe error appears to be in '/Users/greek_fire/.ansible/collections/ansible_collections/theforeman/foreman/roles/operatingsystems/tasks/main.yml': line 23, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: 'Set default templates for Operatingsystems'\n  ^ here\n"}
```
