### ISSUE TITLE
redhat_manifest does not handle changes correctly

### ISSUE THREAD

**Issue by myllynen** [theforeman/foreman-ansible-modules#1473]
##### SUMMARY
When downloading a manifest with `redhat_manifest` the file is always updated and the status from the task is always ok.

When the local file is not present and manifest is downloaded the task status should be changed.

If running a playbook twice to download the manifest ideally the local file should not be updated on the second run when identical.

Here's the snippet I'm using:

```
- name: Get manifest from Red Hat Customer Portal
  redhat.satellite.redhat_manifest:
    uuid: "{{ manifest_uuid }}"
    username: "{{ redhat_portal_username }}"
    password: "{{ redhat_portal_password }}"
    path: /root/satellite_manifest.zip
  register: manifest_download
```

After this `manifest_download is changed` is never true.

Thanks.
