### ISSUE TITLE
Some Modules are not idempotent

### ISSUE THREAD

**Issue by afeefghannam89** [theforeman/foreman-ansible-modules#1482]
##### SUMMARY
Some on the modules are not idempotent. They have have the option **present ** which return always changed as result apart from the existence of the to be configured object. Also they have the option **present_with_defaults** which does not update the the to be configured object, if it exist. Some of these modules are:
sync_plan
repository
activation_key
auth_source_ldap: Here there are only **present** and **absent** as options and present return always changed also when there is no changes on the actual LDAP source.  

I can list more modules later. We are logging the result of the Ansible runs to see who made which changes on which system. So we will get  unreal changes on our RedHat systems, where nothing changed at all. 
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.9.27
```

##### COLLECTION VERSION

```
3.5.0
```

##### KATELLO/FOREMAN VERSION

```
satellite-6.10.6-1.el7sat.noarch
katello-4.1.1-4.el7sat.noarch
foreman-2.5.2.21-1.el7sat.noarch
```

##### EXPECTED RESULTS
To get changed as result only when the configuration of the to be configured object differs from the actual Ansible configuration or when the object does not exist.

**Comment by evgeni** [comment]
There are options that make some modules not idempotent (like setting a password, which we can't check for existence). But they should be documented as such. Have you exact playbook examples that trigger your issues?

**Comment by afeefghannam89** [comment]
I am using a role her some tasks:

```yaml
- name: Create sync plans
  theforeman.foreman.sync_plan:
    name: "{{ item.name }}"
    organization: "{{ item.organization }}"
    description: "{{ item.description | default(omit) }}"
    interval: "{{ item.interval }}"
    enabled: "{{ item.enabled }}"
    sync_date: "{{ item.sync_date }}"
    state: "{{ item.state | default('present') }}"
    cron_expression: "{{ item.cron_expression | default(omit) }}"
    products: "{{ item.products }}"
    server_url: "{{ satellite_url }}"
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
  loop: "{{ sync_plans | default([]) }}"
  when: sync_plans is defined
  
  - name: Enable/disable RHEL repositories with label
  theforeman.foreman.repository_set:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url }}"
    organization: "{{ item.organization }}"
    label: "{{ item.label | default(omit) }}"
    repositories: "{{ item.repositories | default(omit) }}"
    all_repositories: "{{ item.repositories is not defined }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ rhel_repositories | default([]) }}"
  when: rhel_repositories is defined
  
  - name: Create client activation key
  theforeman.foreman.activation_key:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url }}"
    name: "{{ item.name }}"
    organization: "{{ item.organization }}"
    lifecycle_environment: "{{ item.lifecycle_environment }}"
    content_view: "{{ item.content_view }}"
    content_overrides: "{{ item.content_overrides | default(omit) }}"
    auto_attach: "{{ item.auto_attach }}"
    description: "{{ item.description | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    unlimited_hosts: "{{ item.unlimited_hosts }}"
    host_collections: "{{ item.host_collections | default(omit) }}"
    max_hosts: "{{ item.max_hosts | default(omit) }}"
  loop: "{{ activation_Keys | default([]) }}"
  when: activation_Keys is defined
  ```
  
There are more modules, which also not idempotent. I think these modules can not check the status on the target host before making changes.

**Comment by Schluggi** [comment]
We just noticed these modules are not idempotent too:

- theforeman.foreman.auth_source_ldap
- theforeman.foreman.repository

Foreman 3.3.0 / Ansible 6.3.0 (2.13.3) / Collection 3.4.0

**Comment by mdellweg** [comment]
[As stated by @evgeni]These modules are not idempotent when used with parameters that are write-only. And this is well documented:
https://github.com/theforeman/foreman-ansible-modules/blob/develop/plugins/modules/repository.py#L160
https://github.com/theforeman/foreman-ansible-modules/blob/develop/plugins/modules/auth_source_ldap.py#L53

If you rely on the password set and don't want to change it you can do
```yaml
- repository:
    <all fields including passwords>
    state: present_with_defaults
  register: result
- repository:
    <fields without passwords>
    state: present
  if: result is not changed

**Comment by Schluggi** [comment]
> [As stated by @evgeni]These modules are not idempotent when used with parameters that are write-only. And this is well documented: https://github.com/theforeman/foreman-ansible-modules/blob/develop/plugins/modules/repository.py#L160 https://github.com/theforeman/foreman-ansible-modules/blob/develop/plugins/modules/auth_source_ldap.py#L53
> 
> If you rely on the password set and don't want to change it you can do

Thanks for your response but there is some confusion.

### Repository
We don't set `upstream_password` at all:
```yaml
    - name: "Create repository rocky8-appstream"
      theforeman.foreman.repository:
        username: "{{ secrets.foreman_username }}"
        password: "{{ secrets.foreman_password }}"
        server_url: "{{ foreman_server_url }}"
        name: "rocky8-appstream"
        state: present
        content_type: "yum"
        product: "distro-rocky8"
        organization: "Example AG"
        url: "https://ftp.gwdg.de/pub/linux/rocky/8/AppStream/x86_64/os/"
        download_policy: "on_demand"
        mirror_on_sync: false
        gpg_key: "rocky8"
        http_proxy_policy: global_default_http_proxy
      register: result

    - name: Check
      ansible.builtin.debug:
        msg: "no change!"
      when: result.diff.after == result.diff.before
```
The debug message is displayed, so there is no change.

Edit: I added `changed_when: result.diff.after != result.diff.before` to fix this behavior.

### auth_source_ldap 
`present_with_defaults` is only available for repositories but not for `auth_source_ldap`. So we can't use your workaround.

Any other ideas how to fix this?
