### ISSUE TITLE
[Errno 13] Permission denied: '/home/runner/.cache/apypie'

### ISSUE THREAD

**Issue by milodanlso** [theforeman/foreman-ansible-modules#1503]
##### SUMMARY
I'm using theforeman collection to create a virtual machine with the host module (and host_info) with AWX (Ansible Tower).
I have an error : [Errno 13] Permission denied: '/home/runner/.cache/apypie'

##### ISSUE TYPE
When I run my playbook from awx-ee directly through ansible-playbook, it works. The /home/runner/.cache/apypie directory is well created on awx-ee and my virtual machine too.
When using the AWX GUI, I get the following error: Failed to connect to Foreman server: PermissionError: [Errno 13] Permission denied: '/home/runner/.cache/apypie'. I assume that the ~/.cache does not exist (or has restricted rights) on the "temporary container" (I'm not sure of the term) that is created when the awx job is launched.

##### ANSIBLE VERSION
ansible [core 2.12.5.post0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 2.11.3
  libyaml = True

##### COLLECTION VERSION
2.2, 3.6, 3.7

##### STEPS TO REPRODUCE
Create a playbook 
```
- name: "Check {{ serveur_name }} in Foreman"
  theforeman.foreman.host_info:
     username: "{{ foremanuser }}"
     password: "{{ foremanpass }}"
     server_url: "{{ url_foreman }}"
     name: "{{ serveur_name }}"
```

##### EXPECTED RESULTS
Informations about serveur_name 

##### ACTUAL RESULTS
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed to connect to Foreman server: PermissionError: [Errno 13] Permission denied: '/home/runner/.cache/apypie'"}

##### WORKAROUND
set XDG_CACHE_HOME variable in Extra Environment Variables in AWX (example: {"XDG_CACHE_HOME": "/tmp"})
