### ISSUE TITLE
A string equals to password value is hidden

### ISSUE THREAD

**Issue by dpinhas** [theforeman/foreman-ansible-modules#1562]
##### SUMMARY
In a case where a password value equals to a different string, result is hiding the value because it thinks its the password

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible [core 2.14.2]
  config file = None
  configured module search path = ['/Users/dpinhas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/7.2.0/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/dpinhas/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.2 (main, Feb 16 2023, 03:07:35) [Clang 14.0.0 (clang-1400.0.29.202)] (/usr/local/Cellar/ansible/7.2.0/libexec/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### STEPS TO REPRODUCE

```yaml
      redhat.satellite.host_info:
        username: "{{ satellite_username}}"
        password: "{{ satellite_password}}"
        server_url: "{{ satellite_server_url }}"
        search: "*redhat.local"
      register: result
```

##### EXPECTED RESULTS
Differentiate password field from the rest of them. 

##### ACTUAL RESULTS
The result is hidden string even though it is not attended to be hidden.

```
ok: [rhos-ci-satellite] => {"ansible_facts": {"host_list": ["compute-0.********.local", "controller-0.********.local", "undercloud-0.********.local"]}, "changed": false}
```
