### ISSUE TITLE
Syntax for ovirt volume attributes

### ISSUE THREAD

**Issue by agriffit79** [theforeman/foreman-ansible-modules#1564]
What is the correct syntax for specifying volumes when creating an ovirt host? 

I've tried this
```
        compute_attributes:
          cluster: "New"
          memory_mb: 2048
          volumes_attributes:
            - size_gb: 30
              storage_domain: "PROD_A"
              preallocate: "0"
              interface: "ide"
              bootable: true
```
Which generates an ansible error
```
AttributeError: 'list' object has no attribute 'values'\n"
```
And this
```
        compute_attributes:
          cluster: "New"
          memory_mb: 2048
          volumes_attributes:
            0:
              size_gb: 30
              storage_domain: "PROD_A"
              preallocate: "0"
              interface: "ide"
              bootable: true
```
Which Foreman rejects with 
```
ERF42-2471 [Foreman::Exception]: VM volume attributes are not set properly
```
