### ISSUE TITLE
resource_info -> content_view_histories shows Unknown action 'show'

### ISSUE THREAD

**Issue by IncredibleRichie** [theforeman/foreman-ansible-modules#1631]
##### SUMMARY
When i use theforeman.foreman.resource_info
with the resource type: content_view_histories

i get the following error: 

fatal: [occ-main]: FAILED! => {"changed": false, "msg": "Failed to show resource: KeyError: \"Unknown action 'show'. Supported actions: index\""}

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.15.0]
  config file = /etc/ansible/ansible.cfg
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
3.10
```

##### KATELLO/FOREMAN VERSION

```
katello-4.3.1
foreman-3.1.3
```

##### STEPS TO REPRODUCE

```yaml
- name: "Get content_view_history info"
  theforeman.foreman.resource_info:
    username: "{{ admin_user }}"
    password: "{{ admin_password }}"
    server_url: "https://{{ fqdn }}"
    resource: content_view_histories
    params:
      id: "31"
    full_details: true
  register: result
- debug:
    var: result.resources
```

##### EXPECTED RESULTS

CV history Output :-)
##### ACTUAL RESULTS

```

```
