### ISSUE TITLE
Set smart_class_parameter override: false leads to error

### ISSUE THREAD

**Issue by yuqo2450** [theforeman/foreman-ansible-modules#1644]
##### SUMMARY
After setting the _override_ argument of a smart class parameter to _true_ and then reversing it back to _false_ (without changing any other argument) I get an error.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.15.2rc1]
```

##### COLLECTION VERSION

```
theforeman.foreman      3.12.0
```

##### KATELLO/FOREMAN VERSION

```
Foreman 3.2.1
Katello 4.4.2.2
```

##### STEPS TO REPRODUCE

```yaml
- name: Manage SCParams of apply_updates
  theforeman.foreman.smart_class_parameter:
    username: user.name
    password: superSecurePassword
    server_url: "https://foreman.example.com"
    validate_certs: false
    puppetclass_name: yum_cron
    parameter: apply_updates
    state: present
    override: true
    parameter_type: string
    default_value: "somestring"

- name: Manage SCParams of apply_updates
  theforeman.foreman.smart_class_parameter:
    username: user.name
    password: superSecurePassword
    server_url: "https://foreman.example.com"
    validate_certs: false
    puppetclass_name: yum_cron
    parameter: apply_updates
    state: present
    override: false
    parameter_type: "string"
    default_value: "somestring"
```

##### EXPECTED RESULTS
Override should be set to false.

##### ACTUAL RESULTS
Error:
```
Error while performing update on smart_class_parameters:
500 Server Error: Internal Server Error for url:
https://foreman.example.com/foreman_puppet/api/smart_class_parameters/2274
```
Checkmode:
```
--- before
+++ after
@@ -9,10 +9,10 @@
             "merge_default": false,
             "merge_overrides": false,
             "omit": false,
-            "override": true,
+            "override": false,
             "override_value_order": "fqdn\nhostgroup\nos\ndomain",
             "override_values": [],
-            "parameter_type": "string",
+            "parameter_type": "",
             "required": false,
             "validator_type": ""
```
