### ISSUE TITLE
Make katello_repository_set work with label

### ISSUE THREAD

**Issue by sean797** [theforeman/foreman-ansible-modules#166]
##### SUMMARY

currently, I must specify `name` & `product` with `katello_repository_set` module. The latest version of Katello supports searching via label instead of name and product, let's enable that instead - its more user-friendly.

```
  katello_repository_set:
    username: "admin"
    password: "changeme"
    server_url: "https://foreman.example.com"
    verify_ssl: false
    organization: "Default Organization"
    label:  rhel-7-server-extras-rpms
    state: enabled
    repositories:
      - basearch: x86_64
```

##### ISSUE TYPE
 - Feature Idea
