### ISSUE TITLE
Upload multiple rpms with content_upload

### ISSUE THREAD

**Issue by VfBfoerst** [theforeman/foreman-ansible-modules#1678]
##### SUMMARY
Hi :}  
Our foreman can't reach our internal repo-server, therefore we cannot sync the repository with repo-discovery. We need to upload all RPMs using the content_upload module. Since we have a lot of rpms, it would be nice if we could upload all rpms in a given directory, for example:  
  
```yaml
[...]
  src: /given/directory/*.rpms
[...]
```

At the moment, the playbook fails if I try to upload multiple rpms:  
  
```bash
[...]
[Errno 2] No such file or directory: b'/home/ansible/customrpms/*.rpm'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
[...]
```
Uploading a single rpm succeeds.  
Or is there already a way I haven't found yet? :)  

Thank you very much!
##### ISSUE TYPE
 - Feature Idea

**Comment by evgeni** [comment]
Hi,

well, honestly, I think the correct fix is to fix your network to make Foreman be able to access the repo-server?

But failing that, you can use [`with_fileglob` Ansible loop](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/fileglob_lookup.html):
```
- name: "Upload packages"
  theforeman.foreman.content_upload:
    username: "admin"
    password: "changeme"
    server_url: "https://foreman.example.com"
    src: "{{ item }}"
    repository: "Build RPMs"
    product: "My Product"
    organization: "Default Organization"
  with_fileglob:
    - "/srv/rpms/*.rpm"
```
