### ISSUE TITLE
Invalid module options when using role content_view_publish

### ISSUE THREAD

**Issue by lucas-benedito** [theforeman/foreman-ansible-modules#1698]
##### SUMMARY
After implementation from #1676, the role results in a failure due to invalid parameters

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible [core 2.15.1]
```

##### COLLECTION VERSION
```
theforeman.foreman             3.15.0
```

##### STEPS TO REPRODUCE
```yaml
---
- name: Testing async settings
  hosts: localhost
  tasks:
    - ansible.builtin.include_role:
        name: theforeman.foreman.content_view_publish
      vars:
        foreman_content_view_publish_async: 7200
        foreman_content_view_publish_poll: 30
        foreman_server_url: https://testhost
        foreman_organization: "test"
        foreman_username: "admin"
        foreman_password: test
        foreman_content_views:
          - "test"
```

##### EXPECTED RESULTS
Playbook executed with async and poll settings

##### ACTUAL RESULTS
```
TASK [theforeman.foreman.content_view_publish : Publish content views] *********************************************************************************************************************************************************************************************************
failed: [localhost] (item=test) => {"ansible_loop_var": "content_view", "changed": false, "content_view": "test", "msg": "Unsupported parameters for (theforeman.foreman.content_view_version) module: async, poll. Supported parameters include: content_view, current_lifecycle_environment, description, force_promote, force_yum_metadata_regeneration, lifecycle_environments, organization, password, server_url, state, username, validate_certs, version (force)."}
```
