### ISSUE TITLE
redhat.satellite collection removes existing organization parameters while adding a new one on the Satellite server.

### ISSUE THREAD

**Issue by krutikakinge** [theforeman/foreman-ansible-modules#1705]
##### SUMMARY
When trying to add organization parameters on the Satellite server using collection redhat.satellite add the new parameter but removes the old/existing parameters.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

ansible-playbook [core 2.15.8]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.9.18 (main, Sep 22 2023, 17:58:34) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True

##### COLLECTION VERSION
redhat.satellite            3.10.0 

##### STEPS TO REPRODUCE

Create a playbook to add organization parameters on the Satellite server.

```
- name: Add parameter
  hosts: satellite.example.com
  tasks:
    - name: "Set org parameter"
      redhat.satellite.organization:
       username: user
       password: password
       server_url: "https://satellite.example.com"
       name: "organization"
       parameters:
          - name: "foo"
            value: "bar"
```

##### EXPECTED RESULTS

The new parameter should be added along with the existing parameters for the Satellite organization.
##### ACTUAL RESULTS

The old/existing organization parameters are removed and the new parameter is added to the organization.
