### ISSUE TITLE
theforeman.foreman.resource_info Unknown action 'index'. Supported actions: disable, eligible, enable, status

### ISSUE THREAD

**Issue by IncredibleRichie** [theforeman/foreman-ansible-modules#1711]
##### SUMMARY

theforeman.foreman.resource_info seems to use index were no index is allowed

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.15.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.5 (main, Oct 25 2023, 16:19:59) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
theforeman.foreman            4.0.0  

```

##### KATELLO/FOREMAN VERSION

```

foreman-3.9
```

##### STEPS TO REPRODUCE

```yaml
- name: "Read all SCA with full details"
  theforeman.foreman.resource_info:
    <<: *auth_params
    resource: simple_content_access
    full_details: true
  register: result
- debug:
    var: result.resources

```

##### EXPECTED RESULTS

Info about the organizations SCA setting
##### ACTUAL RESULTS

```
TASK [or_smart_proxy_content : Read all SCA with full details] *********************************************
Thursday 22 February 2024  12:43:30 +0100 (0:00:00.075)       0:00:05.057 ***** 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to list resource: KeyError: \"Unknown action 'index'. Supported actions: disable, eligible, enable, status\""}

```
