### ISSUE TITLE
add how to create metadata.json to content_export_library/repository/version

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#1717]
##### SUMMARY
For an export to be usable, it needs a metadata.json (see content_export_info), but the examples do not mention that, or the info module at all, leaving users with unusable exports.

##### ISSUE TYPE
 - Feature Idea

**Comment by sayan3296** [comment]
To add on, In case the format is syncable, We need to generate listing files in the exported content.  When using hammer i.e. 
```
hammer content-export complete library --organization-id 1 --format syncable
```

It takes care of the export and then does the generate-listing as well as generate-metadata action on that export but when using the `redhat.satellite.content_export_*` ansible modules [ or their foreman alternatives ], The listing files are not generated at all [ also the metadata file ].

metadata + listing files -> both needed when we want to import the data via hammer content-import 
listing files only --> Needed when we want to copy the syncable export data in a webserver and use it as a Custom CDN to sync the data from.

**Comment by jtruestedt** [comment]
I also stumbled upon this missing metadata.json and found a way to generate it (with the content_export_info).
Just to add it as example to get the same output like when running hammer, it could look like this in ansible (in this case content view version export)

```
    - name: "Export content view"
      theforeman.foreman.content_export_version:
          username: "{{ foreman_username }}"
          password: "{{ foreman_password }}"
          server_url: "{{ foreman_server_url }}"
          organization: "{{ foreman_organization }}"
          validate_certs: "{{ foreman_validate_certs }}"
          content_view: "{{ foreman_content_view }}"
          content_view_version: "{{ foreman_content_view_version }}"
          incremental: "{{ foreman_incremental }}"
          fail_on_missing_content: True
          format: importable

    - name: "Export content view info"
      theforeman.foreman.content_export_info:
          username: "{{ foreman_username }}"
          password: "{{ foreman_password }}"
          server_url: "{{ foreman_server_url }}"
          organization: "{{ foreman_organization }}"
          validate_certs: "{{ foreman_validate_certs }}"
          content_view: "{{ foreman_content_view }}"
      register: result

    - name: "Write metadata.json to disk using data from the previous task"
      vars:
        metadata: "{{ result['content_exports'][-1]['metadata'] }}"
      ansible.builtin.copy:
        content: "{{ metadata }}"
        dest: "{{ result['content_exports'][-1]['path'] }}/metadata.json"
```
So combining the examples of the export and the export info should work - but it should be mentioned somewhere. But if someone else is looking for something that example might help.
