### ISSUE TITLE
New host parameters don't get added in foreman inventory source

### ISSUE THREAD

**Issue by vladvetu** [theforeman/foreman-ansible-modules#1743]
##### SUMMARY
Manually added host parameters don't get populated in foreman inventory plugin:
```yaml
plugin: theforeman.foreman.foreman
group_prefix: ""
vars_prefix: ""
# Disable because of REPORT API bug https://projects.theforeman.org/issues/37215
# Re-enable when fixed
want_content_facet_attributes: false
# Toggle, if true the inventory will retrieve ‘all_parameters’ information as host vars
want_params: true

# Merge extra vars into the available variables for composition (highest precedence).
use_extra_vars: true

# Toggle, if true the plugin will create Ansible groups for host collections
want_hostcollections: false

# Toggle, if true the inventory will fetch host_groups and create groupings for the same.
want_host_group: true

# Toggle, if true the inventory will fetch location the host belongs to and create groupings for the same.
want_location: true

#Toggle, if true the inventory will fetch organization the host belongs to and create groupings for the same.
want_organization: true

# Toggle, if True the plugin will retrieve host facts from the server
want_facts: false
```
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
❯ ansible --version
ansible [core 2.16.7]
...  
  executable location = /usr/bin/ansible
  python version = 3.11.9 (main, Apr 08 2024, 06:18:15) [GCC] (/usr/bin/python3.11)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION
```
❯ ansible-galaxy collection list | grep foreman
theforeman.foreman                       4.0.0
```

##### KATELLO/FOREMAN VERSION
```
rpm -q rubygem-katello foreman
rubygem-katello-4.12.0-1.el8.noarch
foreman-3.10.0-1.el8.noarch
```

##### STEPS TO REPRODUCE

1. Add a new host parameter through the web UI.
2. Go to Monitor -> Reports -> Reports Templates -> Ansible - Ansible Inventory -> Generate
3. set ```Output format: JSON``` , ```Hosts: <your_host_with_new_params>```, ```Host Parameters: yes``` -> Generate
4. Insepct the JSON and confirm that the new parameters exist.
5. invoke ```ansible-inventory -i foreman.yml --host <host_with_the_new_param>```
6. Check the ouput (the parameters are missing)

##### EXPECTED RESULTS
The new parameter to show in the hostvars.

##### ACTUAL RESULTS
The newly added host parameter does not get populated in the inventory

I feel like I'm missing something because the values are correctly shown in ```Host View -> Ansible -> Inventory```
