### ISSUE TITLE
Payload too large error while using manifest module

### ISSUE THREAD

**Issue by afeefghannam89** [theforeman/foreman-ansible-modules#1768]
##### SUMMARY
I get the folowing error while using the manifest module: 

```
 FAILED! => {"changed": false, "msg": "GET to https://subscription.rhsm.redhat.com/subscription/users/********/owners failed, got HTTP Error 413: Payload Too Large"}
 ```
 Manifest refresh in the UI is working correctly, that is why I think, the usage of proxy in front of our RedHat Satellite is not the cause of this error. This module was working without issues in the past.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.15.9]
python version = 3.11.5 
```

##### COLLECTION VERSION
```
Tested with v4.1.0 and 3.11.0
```

##### KATELLO/FOREMAN VERSION
```
rubygem-katello-4.9.0.25-1.el8sat.noarch
foreman-3.7.0.13-1.el8sat.noarch

```

##### Playbook
```yaml
- name: Export the RedHat manifest
  theforeman.foreman.redhat_manifest:
    uuid: "UUID_Number"
    content_access_mode: "org_environment"
    username: "User_Name"
    password: "Password"
    path: "Path"
  environment: "{{ surf_proxy }}"
  register: manifest_export_result

```
