### ISSUE TITLE
job_template overrides provider_type from template meta-data

### ISSUE THREAD

**Issue by m-bucher** [theforeman/foreman-ansible-modules#181]
##### SUMMARY
When adding a new Ansible Job-template, without explicitly specifiying 'provider_type', the provider_type will always be set to 'SSH'

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
n.a.
```

##### KATELLO/FOREMAN VERSION

```
n.a.
```

##### NAILGUN VERSION

```
n.a.
```

##### STEPS TO REPRODUCE

```yaml
---
- name: "Add Ansible job template"
  foreman_job_template:
    username: "admin"
    password: "secret"
    server_url: "https://foreman.example.com"
    verify_ssl: "no"
    locations: "local"
    organizations: "ACME"
    state: "present"
    template: |
        <%#
        name: Ansible Roles - Ansible Default
        job_category: Ansible Playbook
        description_format: Run Ansible roles
        feature: ansible_run_host
        snippet: false
        provider_type: Ansible
        kind: job_template
        model: JobTemplate
        %>
        ---
        - hosts: all
          tasks:
            - name: Display all parameters known for the Foreman host
              debug:
                var: foreman_params
          roles:
        <%- if @host.all_ansible_roles.present? -%>
        <%=   @host.all_ansible_roles.map { |role| "    - #{role.name.strip}" }.join("\n") %>
        <%- end -%>
    ...
...
```

##### EXPECTED RESULTS

`provider_type` set to `Ansible`

##### ACTUAL RESULTS

`provider_type` set to `SSH`
