### ISSUE TITLE
[repository] ignorable_content should be one of srpm, treeinfo

### ISSUE THREAD

**Issue by EmptyByte** [theforeman/foreman-ansible-modules#1856]
##### SUMMARY

In `repository` module, `ignorable_content`  parameter it says: 

```text
Must be subset of rpm,drpm,srpm,distribution,erratum.
```

https://docs.ansible.com/ansible/latest/collections/theforeman/foreman/repository_module.html#ansible-collections-theforeman-foreman-repository-module

but only srpm and treeinfo are allowed

```yaml
  msg: 'Failed to ensure entity state: ForemanApiException: Error while performing create on repositories: 422 Client Error: 
  Unprocessable Content for url: https://xxxx/katello/api/repositories 
  - {''displayMessage'': ''Validation failed: Ignorable content Invalid value specified for ignorable content. Permissible values srpm,treeinfo'', ''errors'': 
  {''ignorable_content'': [''Invalid value specified for ignorable content. Permissible values srpm,treeinfo'']}}'
```

Documentation should say:

```text
Must be subset of srpm,treeinfo.
```

##### ISSUE TYPE
 - Feature Idea
