### ISSUE TITLE
[subscription_manifest] Idempotency

### ISSUE THREAD

**Issue by EmptyByte** [theforeman/foreman-ansible-modules#1858]
##### SUMMARY

`subscription_manifest` module is unfortunately not that idempotent. It relies on hammer that will trigger failures on re-runs. It is mostly cosmetic:

```bash
Import is the same as existing data The following conflicts were found: [ MANIFEST_SAME ]
```

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
$ ansible --version
ansible [core 2.16.14]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.9 (main, Feb  4 2025, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-4)] (/usr/bin/python3.12)
  jinja version = 3.1.5
  libyaml = True
```

##### COLLECTION VERSION

```
Collection        Version
----------------- -------
ansible.posix     1.6.1
community.general 9.5.7
redhat.satellite  5.3.0
```

##### KATELLO/FOREMAN VERSION

```
rubygem-katello-4.16.0.2-1.el9sat.noarch
foreman-3.14.0.2-1.el9sat.noarch
```

##### STEPS TO REPRODUCE

```yaml
        - name: Upload latest Satellite manifest
          redhat.satellite.subscription_manifest:
            server_url: "https://{{ ansible_fqdn }}"
            username: "{{ satellite_admin_username }}"
            password: "{{ satellite_admin_password }}"
            organization: "{{ satellite_organization }}"
            validate_certs: false
            state: present
            manifest_path: >-
              {{
                (lookup('ansible.builtin.fileglob',
                          playbook_dir ~ '/files/manifests/' ~ ansible_fqdn ~ '/manifest_*.zip',
                          wantlist=True) | sort) | last
              }}
          failed_when: >-
            lookup('ansible.builtin.fileglob',
                    playbook_dir ~ '/files/manifests/' ~ ansible_fqdn ~ '/manifest_*.zip',
                    wantlist=True) | length == 0
```

##### EXPECTED RESULTS

Silently skipped. Not spamming  notifications and fill database with attempts.
