### ISSUE TITLE
Module theforeman.foreman.content_upload  gives 500 internal server error when trying to upload rpm file to Red Hat Satellite version 6.16

### ISSUE THREAD

**Issue by rh-manash** [theforeman/foreman-ansible-modules#1863]
##### SUMMARY
Module theforeman.foreman.content_upload  gives 500 internal server error when trying to upload rpm file to Red Hat Satellite version 6.16.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.18.3]
  config file = ansible.cfg
  configured module search path = ['/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = /.ansible/collections:/usr/share/ansible/collections
  executable location = /.local/bin/ansible
  python version = 3.13.3 (main, Apr 22 2025, 00:00:00) [GCC 15.0.1 20250418 (Red Hat 15.0.1-0)] (/usr/bin/python3)
  jinja version = 3.1.6
  libyaml = True

```

##### COLLECTION VERSION

```
$ ansible-galaxy collection list | grep foreman
theforeman.foreman                       4.2.0
```

##### KATELLO/FOREMAN VERSION

```
# rpm -q rubygem-katello foreman
rubygem-katello-4.14.0.13-1.el9sat.noarch
foreman-3.12.0.8-1.el9sat.noarch
```

##### STEPS TO REPRODUCE

```yaml
- name: "Upload rpm"
  theforeman.foreman.content_upload:
    username: "{{ satellite_user }}"
    password: "{{ satellite_pass }}"
    server_url: "https://{{ satellite_url }}"
    organization: "{{ satellite_org }}"
    validate_certs: no
    src: "{{ rpmfile_full_path_to_upload }}"
    repository: "{{ satellite_repo_where_to_upload }}"
    product: "{{ satellite_product_where_to_upload }}"
```

##### EXPECTED RESULTS

Rpm file should be uploaded to the satellite server.

##### ACTUAL RESULTS

```
TASK [satellite-upload-content-to-repo : Upload rpm] *************************************************************************
failed:  ...output omitted….
"{“/perccli-007.2313.0000.0000-1.noarch.rpm"}, "msg": "Error while performing update on content_uploads: 500 Server Error: Internal Server Error for url: https://mysatelliteserverurl/katello/api/repositories/60/content_uploads/0123sdajhfdjsfhvv"}
```
