### ISSUE TITLE
[content_export_version] Not generating metadata.json for content views and composite content views 

### ISSUE THREAD

**Issue by EmptyByte** [theforeman/foreman-ansible-modules#1864]
##### SUMMARY

The `redhat.satellite.content_export_version` does not generate the metadata.json when exporting content views and composite  content views. 

Also, CCVs are not exported as a normal content views either.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
# ansible --version
ansible [core 2.16.14]
  config file = /root/redhat_satellite-master/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /root/redhat_satellite-master/collections
  executable location = /bin/ansible
  python version = 3.12.9 (main, Feb  4 2025, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-4)] (/usr/bin/python3.12)
  jinja version = 3.1.5
  libyaml = True
```

##### COLLECTION VERSION

```
# /root/redhat_satellite-master/collections/ansible_collections
Collection        Version
----------------- -------
ansible.posix     1.6.1
community.general 9.5.7
redhat.satellite  5.3.0
```

##### KATELLO/FOREMAN VERSION

```
# rpm -q rubygem-katello foreman ruby
rubygem-katello-4.16.0.2-1.el9sat.noarch
foreman-3.14.0.2-1.el9sat.noarch
ruby-3.0.7-165.el9_5.x86_64
```

```
# foreman-rake about
About your application's environment
Rails version             7.0.8.7
Ruby version              ruby 3.0.7p220 (2024-04-23 revision 724a071175) [x86_64-linux]
RubyGems version          3.2.33
Rack version              2.2.14
Middleware                SecureHeaders::Middleware, ActionDispatch::HostAuthorization, ActionDispatch::SSL, Rack::Sendfile, ActionDispatch::Executor, ActiveSupport::Cache::Strategy::LocalCache::Middleware, Rack::Runtime, Rack::MethodOverride, Katello::PreventJsonParsing, ActionDispatch::RequestId, ActionDispatch::RemoteIp, Foreman::Middleware::LoggingContextRequest, Sprockets::Rails::QuietAssets, Rails::Rack::Logger, ActionDispatch::ShowExceptions, ActionDispatch::DebugExceptions, ActionDispatch::Callbacks, ActionDispatch::Cookies, ActionDispatch::Session::ActiveRecordStore, Foreman::Middleware::LoggingContextSession, ActionDispatch::Flash, ActionDispatch::ContentSecurityPolicy::Middleware, ActionDispatch::PermissionsPolicy::Middleware, Rack::Head, Rack::ConditionalGet, Rack::ETag, Rack::TempfileReaper, Apipie::Middleware::ChecksumInHeaders, Foreman::Middleware::Telemetry, Foreman::Middleware::LibvirtConnectionCleaner, ActionDispatch::Static, ActionDispatch::Static, ActionDispatch::Static, ActionDispatch::Static, ActionDispatch::Static, ActionDispatch::Static, ActionDispatch::Static, ActionDispatch::Static, ActionDispatch::Static, ActionDispatch::Static, ActionDispatch::Static, ActionDispatch::Static, ActionDispatch::Static, ActionDispatch::Static, ActionDispatch::Static, Apipie::StaticDispatcher, ApipieDSL::StaticDispatcher, ActionDispatch::Static, ActionDispatch::Static, Katello::Middleware::EventDaemon, Katello::Middleware::OrganizationCreatedEnforcer
Application root          /usr/share/foreman
Environment               production
Database adapter          postgresql
Database schema version   20250309121956
```

##### STEPS TO REPRODUCE

```yaml
    - name: Export CCVs versions
      redhat.satellite.content_export_version:
        server_url: "{{ satellite_server_url | d(omit, true) }}"
        validate_certs: "{{ satellite_validate_certs | d(omit, true) }}"
        username: "{{ satellite_admin_username | d(omit, true) }}"
        password: "{{ satellite_admin_password | d(omit, true) }}"
        organization: "{{ satellite_organization }}"
        content_view: "{{ item.content_view }}"
        content_view_version: "{{ item.content_view_version }}"
        incremental: false
        destination_server: "{{ destination_server | d(omit, true) }}"
        fail_on_missing_content: true
        format: "importable"
      loop: "{{ export_list }}"
      loop_control:
        label: "{{ item.content_view }} v{{ item.content_view_version }}"
```

##### EXPECTED RESULTS

1. A metadata.json generated when exporting a CV or CCV.

Do it manually via the CLI:
```
hammer content-export list
hammer content-export generate-metadata --id 2
 ```

2. The CCV exported as a normal CV (as per the Red Hat Knowledge guide).

##### ACTUAL RESULTS

- CCV is not exported as normal CV
- metadata.json is not generated for both CV or CCV
