### ISSUE TITLE
foreman-ansible hostgroup module returns changed when there is no change

### ISSUE THREAD

**Issue by mukaertida** [theforeman/foreman-ansible-modules#1865]
##### SUMMARY

When creating a new hostgroup that inherits ansible roles from the parent hostgroup, when a new role is defined for the childgroup (that is not listed in the parent roles), ansible returns "changed" for every run of the playbook. This is a bug, for the second run on the same system ansible should return "ok".

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.16.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.8 (main, Dec 12 2024, 09:41:14) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] (/usr/bin/python3.12)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
# /root/.ansible/collections/ansible_collections
Collection            Version
--------------------- -------
ansible.utils         5.1.2  

# /usr/share/ansible/collections/ansible_collections
Collection            Version
--------------------- -------
ansible.posix         1.5.4  
community.general     8.3.0  
theforeman.foreman    4.0.0  
theforeman.operations 3.0.0  
```

##### KATELLO/FOREMAN VERSION

```
rubygem-katello-4.13.1-152.10.0.atix.el8.noarch
foreman-3.11.2-105.1.1.atix.el8.noarch
```

##### STEPS TO REPRODUCE

Wehn running the second task which creates the nested hostgroup "test" that assigns a new ansible role that is not listed in the parent hostgroup, ansible returns always 'changed' for every run, no matter if there is a change on the endsystem or not. This is a bug, for the second run it should return 'ok'.

```yaml

- hosts: localhost
  vars:
    connection: local
  tasks:
    - name: "Create base Hostgroups"
      theforeman.foreman.hostgroup:
        name: "base"
        server_url: "{{ foreman }}"
        username: "{{ user }}"
        password: "{{ passwd }}"
        organization: atix
        ansible_roles:
          - testrole

- hosts: localhost
  vars:
    connection: local
  tasks:
    - name: "Create nested Hostgroups"
      theforeman.foreman.hostgroup:
        name: "test"
        server_url: "{{ foreman }}"
        username: "{{ user }}"
        password: "{{ passwd }}"
        organization: atix
        ansible_roles:
          - foreman.foreman_open_scap
        parent: "base"
```

##### EXPECTED RESULTS

Expect ansible to return in the second run 'ok'.
##### ACTUAL RESULTS

Ansible always returns 'changed'.

```

```
