### ISSUE TITLE
Documentation activation_key content_overrides label wrong format

### ISSUE THREAD

**Issue by mikehulsman** [theforeman/foreman-ansible-modules#1874]
I encountered problems when using the `content_overrides` example in the documentation.
The label is described to have the content ```rhel-7-server-optional-rpms```
But according to https://access.redhat.com/solutions/6370541 it should be ```<organizationLabel>_<productLabel>_<repositoryLabel>```
Tested this and the ```<organizationLabel>_<productLabel>_<repositoryLabel>``` is the proper format.

**Comment by EmptyByte** [comment]
@mikehulsman yes but only for custom products/repos:

```
    content_overrides:
      - label: 'rhel-9-for-x86_64-baseos-rpms'
        override: 'enabled'
      - label: 'rhel-9-for-x86_64-appstream-rpms'
        override: 'enabled'
      - label: 'satellite-client-6-for-rhel-9-x86_64-rpms'
        override: 'enabled'
      - label: 'codeready-builder-for-rhel-9-x86_64-rpms'
        override: 'disabled'
      - label: 'acme_custom_rhel9'
        override: 'disabled'
```
