### ISSUE TITLE
foreman_setting is not idempotent

### ISSUE THREAD

**Issue by akofink** [theforeman/foreman-ansible-modules#195]
##### SUMMARY

All modules should be able to be run multiple times with only one side effect. In this case, we should check the setting's value and compare it with the requested value in the playbook.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.6.5
  config file = /home/akofink/dev/repos/katello-ansible-seeds/ansible.cfg
  configured module search path = [u'/home/akofink/dev/repos/katello-ansible-seeds/foreman-ansible-modules/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Sep 21 2018, 23:26:48) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
```

##### KATELLO/FOREMAN VERSION
devel (foreman/katello running from source)

```
$ rpm -q tfm-rubygem-katello foreman
package tfm-rubygem-katello is not installed
package foreman is not installed

$ git rev-parse HEAD # foreman
ad28e6bb7bfcbc5abf14833ec1e401cef1134cc1
$ git rev-parse HEAD # katello
ee0b953e1994a538f0ea65d7363a35560e2db205
```

##### NAILGUN VERSION

```
Version: 0.31.0
```

##### STEPS TO REPRODUCE

Run this playbook:

```yaml
  - name: Increase idle_timeout to 1 week
    foreman_setting:
      username: "{{ foreman_username }}"
      password: "{{ foreman_password }}"
      server_url: "{{ foreman_server_url }}"
      verify_ssl: "{{ foreman_verify_ssl }}"
      name: idle_timeout
      value: 10080
  - name: Increase idle_timeout to 1 week
    foreman_setting:
      username: "{{ foreman_username }}"
      password: "{{ foreman_password }}"
      server_url: "{{ foreman_server_url }}"
      verify_ssl: "{{ foreman_verify_ssl }}"
      name: idle_timeout
      value: 10080
```

##### EXPECTED RESULTS

The first time a value is changed, ansible reports `changed: true`; on subsequent runs, it reports `changed: false`.

##### ACTUAL RESULTS

The first time a value is changed, ansible reports `changed: true`; on subsequent runs, it reports `changed: true`.

```
TASK [Increase idle_timeout to 1 week] ****************************************************************************************************************************************************************************
task path: /home/akofink/dev/repos/katello-ansible-seeds/seed.yml:8                                                                                                                                                
changed: [localhost] => {"changed": true, "foreman_setting": {"created_at": "2018-10-24 20:11:10 UTC", "default": 60, "description": "Log out idle users after a certain number of minutes", "id": 117, "name": "id
le_timeout", "settings_type": "integer", "updated_at": "2018-10-25 12:52:22 UTC", "value": 10080}}
TASK [Increase idle_timeout to 1 week] ****************************************************************************************************************************************************************************
task path: /home/akofink/dev/repos/katello-ansible-seeds/seed.yml:8                                                                                                                                                
changed: [localhost] => {"changed": true, "foreman_setting": {"created_at": "2018-10-24 20:11:10 UTC", "default": 60, "description": "Log out idle users after a certain number of minutes", "id": 117, "name": "id
le_timeout", "settings_type": "integer", "updated_at": "2018-10-25 12:52:22 UTC", "value": 10080}}
```
