### ISSUE TITLE
How to check off "Include all RPMs with no errata." in rpm filter type (katello_content_view_filter).

### ISSUE THREAD

**Issue by larizzo** [theforeman/foreman-ansible-modules#196]
##### SUMMARY
I'm trying to figure out how to check off the "Include all RPMs with no errata." in the rpm filter type. Either I'm not seeing it (very likely) or it's not possible or not documented.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.6.4
  config file = /home/t156830/.ansible.cfg
  configured module search path = [u'/home/t156830/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /cnunix/integ/ansible/SAT63/sat_venv/lib/python2.7/site-packages/ansible
  executable location = /cnunix/integ/ansible/SAT63/sat_venv/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### KATELLO/FOREMAN VERSION
```
tfm-rubygem-katello-3.4.5.86-1.el7sat.noarch
foreman-1.15.6.48-1.el7sat.noarch

```

##### NAILGUN VERSION
```
Version: 0.31.0
```

##### STEPS TO REPRODUCE

```yaml
  - name: "Create filter {{ item.name }} for {{ item.content_view }} content view"
    katello_content_view_filter:
      server_url: "https://{{satelliteurl}}"
      username: "{{ sat_username }}"
      password: "{{ sat_password }}"
      verify_ssl: false
      name: "{{ item.name }}"
      content_view: "{{ item.content_view }}"
      organization: "ITUX"
      filter_type: "{{ item.filter_type }}"
      inclusion: "true"
      rule_state: "absent"
```

##### EXPECTED RESULTS
Check off the box "Include all RPMs with no errata." in the RPM filter type.
