### ISSUE TITLE
 katello_repository_set error: A value must be provided for the "product" field.

### ISSUE THREAD

**Issue by flyemsafe** [theforeman/foreman-ansible-modules#232]
##### SUMMARY

Enabling repository sets results in error; A value must be provided for the "product" field.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.7.7
```

##### KATELLO/FOREMAN VERSION

```
tfm-rubygem-katello-3.10.0.19-1.el7sat.noarch
```

##### NAILGUN VERSION

```
Version: 0.30.2
```

yes
##### STEPS TO REPRODUCE

```yaml
- name: "Enable repository sets"
  katello_repository_set:
    username: "{{ configure_katello_username }}"
    password: "{{ configure_katello_password }}"
    server_url: "{{ configure_katello_server_url }}"
    verify_ssl: "{{ configure_katello_verify_ssl }}"
    name: "Red Hat Enterprise Linux 7 Server (RPMs)"
    product: "Red Hat Enterprise Linux Server"
    organization: ACME
    repositories:
    - releasever: "7Server"
      basearch: "x86_64"
    state: enabled
```
```

##### EXPECTED RESULTS
<!--- What did you expect to happen when running the steps above? -->

Repository sets enabled.

##### ACTUAL RESULTS
<!--- What actually happened? If possible run with extra verbosity (-vvvv) -->

<!--- Paste verbatim command output between quotes below -->
```
task path: /home/rheron/.ansible/roles/rodhouse/publish/ansible-role-configure-katello/tasks/repositories.yml:2
Using module file /home/rheron/.ansible/modules/foreman-ansible-modules/modules/katello_repository_set.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: rheron
<localhost> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-vujvdphxeckwmkdkqlddcjuyyrapyobs; /usr/bin/python'"'"' && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 113, in <module>
  File "<stdin>", line 105, in _ansiballz_main
  File "<stdin>", line 48, in invoke_module
  File "/tmp/ansible_katello_repository_set_payload_3_Zh7Z/__main__.py", line 232, in <module>
  File "/tmp/ansible_katello_repository_set_payload_3_Zh7Z/__main__.py", line 228, in main
  File "/tmp/ansible_katello_repository_set_payload_3_Zh7Z/ansible_katello_repository_set_payload.zip/ansible/module_utils/basic.py", line 2369, in fail_json
  File "/tmp/ansible_katello_repository_set_payload_3_Zh7Z/ansible_katello_repository_set_payload.zip/ansible/module_utils/basic.py", line 2341, in _return_formatted
  File "/tmp/ansible_katello_repository_set_payload_3_Zh7Z/ansible_katello_repository_set_payload.zip/ansible/module_utils/basic.py", line 522, in remove_values
  File "/tmp/ansible_katello_repository_set_payload_3_Zh7Z/ansible_katello_repository_set_payload.zip/ansible/module_utils/basic.py", line 505, in _remove_values_conditions
TypeError: Value of unknown type: <type 'exceptions.TypeError'>, A value must be provided for the "product" field.

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 113, in <module>\n  File \"<stdin>\", line 105, in _ansiballz_main\n  File \"<stdin>\", line 48, in invoke_module\n  File \"/tmp/ansible_katello_repository_set_payload_3_Zh7Z/__main__.py\", line 232, in <module>\n  File \"/tmp/ansible_katello_repository_set_payload_3_Zh7Z/__main__.py\", line 228, in main\n  File \"/tmp/ansible_katello_repository_set_payload_3_Zh7Z/ansible_katello_repository_set_payload.zip/ansible/module_utils/basic.py\", line 2369, in fail_json\n  File \"/tmp/ansible_katello_repository_set_payload_3_Zh7Z/ansible_katello_repository_set_payload.zip/ansible/module_utils/basic.py\", line 2341, in _return_formatted\n  File \"/tmp/ansible_katello_repository_set_payload_3_Zh7Z/ansible_katello_repository_set_payload.zip/ansible/module_utils/basic.py\", line 522, in remove_values\n  File \"/tmp/ansible_katello_repository_set_payload_3_Zh7Z/ansible_katello_repository_set_payload.zip/ansible/module_utils/basic.py\", line 505, in _remove_values_conditions\nTypeError: Value of unknown type: <type 'exceptions.TypeError'>, A value must be provided for the \"product\" field.\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

PLAY RECAP ***********************************************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=1   
```
