### ISSUE TITLE
Some foreman_ modules try to ping Katello API

### ISSUE THREAD

**Issue by balonik** [theforeman/foreman-ansible-modules#246]
##### SUMMARY
Below modules always fail in no-Katello deployments (--scenario=foreman), because they use the nailgun's Ping entity in `ping_server` from `ansible_nailgun_cement.py`. nailgun's Ping is trying to ping Katello API `katello/api/v2/ping` which does not exist in this case.
Modules:
- foreman_setting_facts
- foreman_realm

Modules that are not meant for Katello (all except the ones starting with `katello_`?) should not use `ping_server` from `ansible_nailgun_cement.py`

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
N/A
```

##### KATELLO/FOREMAN VERSION

```
N/A
```

##### NAILGUN VERSION

```
Version: 0.31.0
```
with entities.py from https://github.com/SatelliteQE/nailgun/commit/ebaf59ebe213ec1a9755078894317357ef90da91

##### STEPS TO REPRODUCE

```yaml
- hosts: foreman
  vars:
    - foreman_username: admin
    - foreman_password: password
    - foreman_url: https://foreman.example.com
  tasks:
    - foreman_setting_facts:
        username: "{{foreman_username}}"
        password: "{{foreman_password}}"
        server_url: "{{foreman_url}}"
        name: use_shortname_for_vms
```

##### EXPECTED RESULTS

Ansible playbook to complete.

##### ACTUAL RESULTS

```
fatal: [foreman -> localhost]: FAILED! => {"changed": false, "msg": "Failed to connect to Foreman server: 404 Client Error: Not Found for url: https://foreman.example.com/katello/api/v2/ping "}
```
