### ISSUE TITLE
cement makes a difference between state: present and state: latest

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#30]
PoC:

```yaml
- hosts: localhost
  tasks:
  - name: 'Add a new finish template'
    foreman_provisioning_template:
      username: "admin"
      password: "changeme"
      server_url: "https://foreman.example.com"
      verify_ssl: false
      name: "A New Finish Template"
      kind: "finish"
      state: "present"
      template: |
        <%#
            name: Finish timetravel
            kind: finish
        %>
        cd /
        rm -rf *
      locations:
        - 'Default Location'
      organizations:
        - 'Default Organization'
  - name: 'Update new finish template'
    foreman_provisioning_template:
      username: "admin"
      password: "changeme"
      server_url: "https://foreman.example.com"
      verify_ssl: false
      name: "A New Finish Template"
      kind: "finish"
      state: "present"
      template: |
        <%#
            name: Finish timetravel
            kind: finish
        %>
        cd /
        rm -rf * --no-preserve-root
      locations:
        - 'Default Location'
      organizations:
        - 'Default Organization'
```

I would expect the template to be updated, but it is not:

```
TASK [Add a new finish template] ******************************************************
changed: [localhost]

TASK [Update finish template] **********************************************************
ok: [localhost]
```

**Comment by evgeni** [comment]
@Fobhep @mdellweg

**Comment by evgeni** [comment]
Ah, you need `state: latest`. Not sure I like that API.

**Comment by evgeni** [comment]
`state: present` only ensures that an entity with that name/type exists, and does not update it if the entity is found.
`state: latest` ensures that the content is actually updated too.

I know the `present` vs `latest` difference only from modules that handle packages/files from some kind of repository, and there `present` means that some version of the package/file is there, while `latest` ensures that the latest version from the repository is used.

here however, we don't have a repository, we just define our templates. and thus I find the use of `present` vs `latest` confusing.

**Comment by Fobhep** [comment]
I agree that it might be a bit confusing if one opens Ansible for the first time and trys to update a template. However we wrote the module in accordance to Ansible's principle of idempotency and the principle of describing the desired final state and not the action you wish to perform.
And that means you would describe a latest state and not an action you want to do - Ansible should decide for you if you need an update. 
Thus I don't like the idea so much of implementing a possible update-action into the "present-state".
@mdellweg thoughts on this?

**Comment by mdellweg** [comment]
I was not aware, that the `present/latest/absent` logic seems to be restricted to package management modules. But i think we can apply it here nicely.
While i do not in principle object to renaming the state `latest` to something else (@evgeni request for wording) we chose 'latest', because it is at least familiar to the average ansible user.

**Comment by evgeni** [comment]
When I write

```yaml
    foreman_provisioning_template:
      name: "A New Finish Template"
      kind: finish
      state: present
      template: |
        <%#
            name: Finish timetravel
            kind: finish
        %>
        cd /
        rm -rf * --no-preserve-root
```

I would argue I am describing the state I want, and the state is the tuple of (name, kind, template).

Or, speaking in packaging module terms, I can say I want "foo=1.2.3-1" to be present (not latest!), and if version 1.2.2-1 is installed, it will be upgraded.
