### ISSUE TITLE
katello_repository_set repo selection

### ISSUE THREAD

**Issue by jwbernin** [theforeman/foreman-ansible-modules#333]
##### SUMMARY
When specifying a releasever for a repo that is unversioned (e.g. rhel-7-server-extras-rpms), the module reports "ok" without making any changes. It should either error out, or allow a "not versioned" designator (e.g. releasever: "*") to accommodate looping over variables.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/nfshome/jberning/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr  3 2019, 17:26:03) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]


```

##### KATELLO/FOREMAN VERSION

```
tfm-rubygem-katello-3.10.0.46-1.el7sat.noarch
foreman-1.20.1.34-1.el7sat.noarch

```

##### NAILGUN VERSION

```
$ pip3 show nailgun | grep Version
Version: 0.32.0

```

##### STEPS TO REPRODUCE

```yaml
---
- name: enable repos on Satellite
  hosts: localhost
  vars:
    satellite_host: newsat.ncphotography.lan
    satellite_user: admin
    satellite_password: admin
    org_name: NCP
    repos:
      - name: rhel-7-server-ansible-2.6-rpms
        arch: x86_64
      - name: ansible-2.8-for-rhel-8-x86_64-rpms
        arch: x86_64
      - name: rhel-7-server-extras-rpms
        arch: x86_64
      - name: rhel-7-server-optional-rpms
        arch: x86_64
        release: 7Server
      - name: rhel-7-server-rpms
        arch: x86_64
        release: 7Server


  tasks:

    - name: Enable Upstream repositories
      katello_repository_set:
        username: "{{ satellite_user }}"
        password: "{{ satellite_password }}"
        server_url: "https://{{ satellite_host }}"
        verify_ssl: false
        organization: "{{ org_name }}"
        label: "{{ item.name }}"
        repositories:
          - releasever: "{{ item.release | default ('')}}"
            basearch: "{{ item.arch }}"
        state: enabled
      loop: "{{ repos }}"
```

##### EXPECTED RESULTS

All five repos in the loop enabled, including those with no release version

##### ACTUAL RESULTS

First three repos were marked "ok" and no changes were made.

```
PLAY [enable repos on Satellite] ***********************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Enable Upstream repositories] ********************************************
ok: [localhost] => (item={'name': 'rhel-7-server-ansible-2.6-rpms', 'arch': 'x86_64', 'release': '7Server'})
ok: [localhost] => (item={'name': 'ansible-2.8-for-rhel-8-x86_64-rpms', 'arch': 'x86_64'})
ok: [localhost] => (item={'name': 'rhel-7-server-extras-rpms', 'arch': 'x86_64'})
 [WARNING]: Use of deprecated method parse_params


PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

[jberning@ansdev ansible]$ vi test2.yml 
[jberning@ansdev ansible]$ vi test2.yml 
[jberning@ansdev ansible]$ ansible-playbook test2.yml 

PLAY [enable repos on Satellite] ***********************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Enable Upstream repositories] ********************************************
ok: [localhost] => (item={'name': 'rhel-7-server-ansible-2.6-rpms', 'arch': 'x86_64'})
ok: [localhost] => (item={'name': 'ansible-2.8-for-rhel-8-x86_64-rpms', 'arch': 'x86_64'})
ok: [localhost] => (item={'name': 'rhel-7-server-extras-rpms', 'arch': 'x86_64'})
changed: [localhost] => (item={'name': 'rhel-7-server-optional-rpms', 'arch': 'x86_64', 'release': '7Server'})
changed: [localhost] => (item={'name': 'rhel-7-server-rpms', 'arch': 'x86_64', 'release': '7Server'})
 [WARNING]: Use of deprecated method parse_params


PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```

**Comment by jwbernin** [comment]
Can be worked around using conditionals, but doing so forces two plays with the same module for what is in effect a single loop. This playbook works:
```
---
- name: enable repos on Satellite
  hosts: localhost
  vars:
    satellite_host: newsat.ncphotography.lan
    satellite_user: admin
    satellite_password: admin
    org_name: NCP
    repos:
      - name: rhel-7-server-ansible-2.6-rpms
        arch: x86_64
      - name: ansible-2.8-for-rhel-8-x86_64-rpms
        arch: x86_64
      - name: rhel-7-server-extras-rpms
        arch: x86_64
      - name: rhel-7-server-optional-rpms
        arch: x86_64
        release: 7Server
      - name: rhel-7-server-rpms
        arch: x86_64
        release: 7Server


  tasks:
    - name: Enable Upstream repositories
      katello_repository_set:
        username: "{{ satellite_user }}"
        password: "{{ satellite_password }}"
        server_url: "https://{{ satellite_host }}"
        verify_ssl: false
        organization: "{{ org_name }}"
        label: "{{ item.name }}"
        repositories:
          - releasever: "{{ item.release | default ('')}}"
            basearch: "{{ item.arch }}"
        state: enabled
      loop: "{{ repos }}"
      when: item.release is defined

    - name: Enable Upstream repositories #2
      katello_repository_set:
        username: "{{ satellite_user }}"
        password: "{{ satellite_password }}"
        server_url: "https://{{ satellite_host }}"
        verify_ssl: false
        organization: "{{ org_name }}"
        label: "{{ item.name }}"
        repositories:
          - basearch: "{{ item.arch }}"
        state: enabled
      loop: "{{ repos }}"
      when: item.release is not defined
```
