### ISSUE TITLE
katello_lifecycle_environment registering change when not changed

### ISSUE THREAD

**Issue by jwbernin** [theforeman/foreman-ansible-modules#334]
##### SUMMARY
When running a playbook with this module, the first run is correct. Subsequent runs note that lifecycle environments have changed, when they have not.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.8.0
  config file = /nfshome/jberning/ansible/ansible.cfg
  configured module search path = ['/nfshome/jberning/Projects/foreman-ansible-modules/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr  3 2019, 17:26:03) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]

```

##### KATELLO/FOREMAN VERSION

```
tfm-rubygem-katello-3.10.0.46-1.el7sat.noarch
foreman-1.20.1.34-1.el7sat.noarch
```

##### NAILGUN VERSION

```
$ pip3 show nailgun | grep Version
Version: 0.32.0

```

##### STEPS TO REPRODUCE

```yaml
---
- name: enable repos on Satellite
  hosts: localhost
  vars:
    satellite_host: newsat.ncphotography.lan
    satellite_user: admin
    satellite_password: admin
    org_name: NCP
    le_pairs:
      - name: Appserver-Dev
      - name: Appserver-Test
        prior: Appserver-Dev
      - name: Appserver-Prod
        prior: Appserver-Test
      - name: Appserver-DR
        prior: Appserver-Prod
      - name: Webserver-Dev
      - name: Webserver-Test
        prior: Webserver-Dev
      - name: Webserver-Prod
        prior: Webserver-Test
      - name: Webserver-DR
        prior: Webserver-Prod
      - name: DBserver-Dev
      - name: DBserver-Test
        prior: DBserver-Dev
      - name: DBserver-Prod
        prior: DBserver-Test
      - name: DBserver-DR
        prior: DBserver-Prod


  tasks:
    - name: Build lifecycle environments
      katello_lifecycle_environment:
        name: "{{ item.name }}"
        organization: "{{ org_name }}"
        prior: "{{ item.prior | default ('Library') }}"
        state: present
        username: "{{ satellite_user }}"
        password: "{{ satellite_password }}"
        server_url: "https://{{ satellite_host }}"
        verify_ssl: false
      loop: "{{ le_pairs }}"

```

##### EXPECTED RESULTS

First run, change LEs. Second run, no changes, all steps "ok"

##### ACTUAL RESULTS

First run:
```
PLAY [enable repos on Satellite] ***********************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Build lifecycle environments] ********************************************
changed: [localhost] => (item={'name': 'Appserver-Dev'})
changed: [localhost] => (item={'name': 'Appserver-Test', 'prior': 'Appserver-Dev'})
changed: [localhost] => (item={'name': 'Appserver-Prod', 'prior': 'Appserver-Test'})
changed: [localhost] => (item={'name': 'Appserver-DR', 'prior': 'Appserver-Prod'})
changed: [localhost] => (item={'name': 'Webserver-Dev'})
changed: [localhost] => (item={'name': 'Webserver-Test', 'prior': 'Webserver-Dev'})
changed: [localhost] => (item={'name': 'Webserver-Prod', 'prior': 'Webserver-Test'})
changed: [localhost] => (item={'name': 'Webserver-DR', 'prior': 'Webserver-Prod'})
changed: [localhost] => (item={'name': 'DBserver-Dev'})
changed: [localhost] => (item={'name': 'DBserver-Test', 'prior': 'DBserver-Dev'})
changed: [localhost] => (item={'name': 'DBserver-Prod', 'prior': 'DBserver-Test'})
changed: [localhost] => (item={'name': 'DBserver-DR', 'prior': 'DBserver-Prod'})
 [WARNING]: Use of deprecated method parse_params


PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```
Second run had identical output.
