### ISSUE TITLE
How to manage parameters

### ISSUE THREAD

**Issue by Fodoj** [theforeman/foreman-ansible-modules#367]
Parameters are nested within many resource types: https://theforeman.org/plugins/katello/3.4/api/apidoc/v2/parameters/create.html.

What would be the way forward to manage them with this module? As part of "parameters" field of parent resource or as a completely separate entity? 

This:

```
foreman_parameter:
  hostgroup: "HG"
  name: "my_param"
  value: "123"
```

Or this:

```
foreman_hostgroup:
  name: "HG"
  parameters:
    - name: "my_param"
      value: "123"
```

?
