### ISSUE TITLE
extend hostgroup module with non-Foreman options

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#374]
> This is great @bagasse! I've added two comments, but nothing major ;)
> 
> As for OpenSCAP, yeah this sounds like a good addition, I don't mind it being in this PR or an own one. Just remember that we'll need to use a different `apidoc.json` then ;)

@evgeni It would be nice to add extensible smart_proxy support if we can. We use katello and it would be nice to add content proxy also, but maybe we have to make a subclass katello_hostgroup for that ? I didn't wanted to make this happen in this PR that I think  is big enough :)

_Originally posted by @bagasse in https://github.com/theforeman/foreman-ansible-modules/pull/366#issuecomment-514528037_

**Comment by evgeni** [comment]
Braindump: I think we should not create a separate katello_hostgroup module, but just extend the existing one and document that some options won't work if a specific plugin (scap, katello, salt, etc) is not installed.

IIRC we have this in some places already. (Or rather: for some modules behavior on Foreman 1.22 is different to the one on 1.21)

**Comment by mdellweg** [comment]
We _almost_ have it for the snapshot plugin / module. ;)
I also vote for a single module for hostgroups. I know, we could add a second test_playbook especially for those features, but i am unsure whether it were a benefit at all, since one would be forced to rerecord that anyway. All in all, i think we would need a good balance for the amount of setup we want to require to rerecord things. At least it should be documented in a very instructive way.

__Brainstorm:__ We could add a script / provide a playbook to do the needed setup in a dedicated forklift box.

**Comment by bagasse** [comment]
@evgeni, @mdellweg, It's fine for me to document plugin specific params on the `foreman_hostgroup` module I think this module is just missing parameters support for bare foreman server type (regarding to apidoc on foreman 1.22 / develop). If we include katello's specific params and some other plugins like openscap, I think missing params for this module are:
* parameters (foreman, param type is still  missing in develop branch, needs a foreman change)
* openscap_proxy (openscap)
* content_source (katello)
* content_view (katello)
* lifecycle_environment (katello)
* kickstart_repository (katello)

I wanted to tacle this in another PR than #366

**Comment by bagasse** [comment]
On the dev setup part, +1 for some playbooks and and boxes in forklift ! For me, setting up dev env for foreman ansible modules is a barrier to contributions, and we have to make it lower as possible. I already postponed some contributions (like this one, it's been a lot of time that I wanted to contribute on this part because we use it extensively) because a lot of modules have to interact with a lot of foreman-proxies components (DNS, compute resource..). I think we have to provide an all-in-one forklift box that permit to make most of the things and use variables in our test playbooks pointing to this setup by default if possible to ease test recording.

For example my current test env for foreman ansible modules is composed of two boxes (that can be merged in one if DNS smart-proxy is included in foreman server, I don't wanted to fix that in the hostgroup PR because it's unrelated). I used forklift to set it up with following changes:

```
cat playbooks/katello_libvirt.yml 
---
- name: Apply katello playbook
  import_playbook: katello.yml
- name: Apply libvirt playbook
  import_playbook: libvirt.yml
```

```
cat vagrant/settings.yaml
---
memory: 4608
cpus: 2
scale_memory: 1
scale_cpus: 1
sync_type: 'rsync'

cachier:
  mount_options: ['rw', 'vers=3', 'tcp', 'nolock']

ssh_forward_agent: True

domain: 'example.com'
```

```
cat vagrant/boxes.d/99-local.yaml
---
foreman:
    box:   centos7
    memory: 6144
    ansible:
      playbook: 'playbooks/katello_libvirt.yml'
      variables:
        foreman_repositories_version: 1.22
        katello_repositories_version: 3.12
        foreman_installer_additional_packages: ['tfm-rubygem-foreman_dhcp_browser', 'tfm-rubygem-foreman_expire_hosts', 'tfm-rubygem-ovirt_provision_plugin', 'katello']
        foreman_installer_options: ['--enable-foreman-compute-openstack', '--enable-foreman-compute-libvirt', '--enable-foreman-compute-ovirt', '--enable-foreman-plugin-openscap']

# for the DNS part, can be merged with the first box
centos7-devel:
    box: centos7
    memory: 2048
    ansible:
      playbook: 'playbooks/foreman_proxy_content.yml'
      group: 'foreman-proxy-content'
      server: foreman
      variables:
        foreman_repositories_version: 1.22
        katello_repositories_version: 3.12
        foreman_installer_options: ['--foreman-proxy-dns=true']
```

but and AIO box for test should look like

```
foreman:
    box:   centos7
    memory: 6144
    ansible:
      playbook: 'playbooks/katello_libvirt.yml'
      variables:
        foreman_repositories_version: 1.22
        katello_repositories_version: 3.12
        foreman_installer_additional_packages:
          - tfm-rubygem-foreman_dhcp_browser
          - tfm-rubygem-foreman_expire_hosts
          - tfm-rubygem-ovirt_provision_plugin
          - katello
        foreman_installer_options:
          - '--enable-foreman-compute-openstack'
          - '--enable-foreman-compute-libvirt'
          - '--enable-foreman-compute-ovirt'
          - '--enable-foreman-plugin-openscap'
          - '--enable-foreman-proxy-plugin-openscap'
          - '--foreman-proxy-dns=true'
          - '--foreman-proxy-bmc=true'
          - '--foreman-proxy-realm'
```
