### ISSUE TITLE
Make contribution to foreman-ansible-modules easier

### ISSUE THREAD

**Issue by bagasse** [theforeman/foreman-ansible-modules#375]
##### SUMMARY

Today, there is no default test env documented or provided. This can be an obstacle to contributions on some parts  of foreman-ansible-modules that need a 'big' setup (read a lot of plugins / proxy features enabled)

Discution started here #374 thanks to @mdellweg.

Ideas:
* Provide All in one forklift box that can be used out of the box to test/record most of foreman-ansible-modules
* Provides sane defaults in `test_playbooks` to point to this setup (foreman server, smart proxies names...)
* Add some docs on README on how to setup this env (link to forlift docs, required forklift settings...)

Some starting points:

```
cat playbooks/foreman_ansible_modules.yml 
---
# foreman-ansible-modules default test env setup
- name: Apply katello playbook
  import_playbook: katello.yml
- name: Apply libvirt playbook
  import_playbook: libvirt.yml
```

```
cat vagrant/settings.yaml
---
memory: 4608
cpus: 2
scale_memory: 1
scale_cpus: 1
sync_type: 'rsync'

cachier:
  mount_options: ['rw', 'vers=3', 'tcp', 'nolock']

ssh_forward_agent: True

domain: 'example.com'
```

```
foreman:
    box:   centos7
    memory: 6144
    ansible:
      playbook: 'playbooks/foreman_ansible_modules.yml'
      variables:
        foreman_repositories_version: 1.22
        katello_repositories_version: 3.12
        foreman_installer_additional_packages:
          - tfm-rubygem-foreman_dhcp_browser
          - tfm-rubygem-foreman_expire_hosts
          - tfm-rubygem-ovirt_provision_plugin
          - katello
        foreman_installer_options:
          - '--enable-foreman-compute-openstack'
          - '--enable-foreman-compute-libvirt'
          - '--enable-foreman-compute-ovirt'
          - '--enable-foreman-plugin-openscap'
          - '--enable-foreman-proxy-plugin-openscap'
          - '--foreman-proxy-dns=true'
          - '--foreman-proxy-bmc=true'
          - '--foreman-proxy-realm'
```

##### ISSUE TYPE
 - Feature Idea
