### ISSUE TITLE
katello_activation_key module is unable to set content_overrides for repositories in custom products

### ISSUE THREAD

**Issue by ogajduse** [theforeman/foreman-ansible-modules#377]
##### SUMMARY

katello_activation_key module is unable to set content_overrides for repositories in custom products but works for every RH repository.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.8.1
  config file = /home/ogajduse/qa_repos/foreman/foreman-ansible-modules/ansible.cfg
  configured module search path = ['/home/ogajduse/qa_repos/foreman/foreman-ansible-modules/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, May 11 2019, 00:38:04) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
```

##### KATELLO/FOREMAN VERSION

```
tfm-rubygem-katello-3.12.0.5-1.el7sat.noarch
foreman-1.22.0.6-1.el7sat.noarch
```

##### NAILGUN VERSION

```
nailgun==0.32.0
```

##### STEPS TO REPRODUCE

```yaml
    - name: Create Pulp Demo Repos Product
      katello_product:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server_url }}"
        verify_ssl: "{{ verify_ssl }}"
        name: Pulp Demo Repos
        organization: "{{org_name }}"
        state: present

    - name: Create test_simple_errata repository
      katello_repository:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server_url }}"
        verify_ssl: "{{ verify_ssl }}"
        name: test_simple_errata
        product: Pulp Demo Repos
        organization: "{{ org_name }}"
        content_type: yum
        url: https://repos.fedorapeople.org/pulp/pulp/demo_repos/test_simple_errata/

    - name: Sync test_simple_errata yum repository
      katello_sync:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server_url }}"
        verify_ssl: "{{ verify_ssl }}"
        organization: "{{ org_name }}"
        product: Pulp Demo Repos
        repository: test_simple_errata
        synchronous: true

    - name: create AK
      katello_activation_key:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server_url }}"
        verify_ssl: "{{ verify_ssl }}"
        name: my-custom-key
        organization: "{{ org_name }}"
        lifecycle_environment: "Library"
        content_view: 'Default Organization View'
        subscriptions:
            - name: Pulp Demo Repos
        content_overrides:
            - label: test_simple_errata
              override: disabled
        auto_attach: true
```

##### EXPECTED RESULTS

The module should create a content override for the specified repository label.
##### ACTUAL RESULTS

The module does not provide idempotence, reports *changed* every time I run it.
