### ISSUE TITLE
katello_content_view_version failed with two lifecycle environments

### ISSUE THREAD

**Issue by sthirugn** [theforeman/foreman-ansible-modules#474]
##### SUMMARY
katello_content_view_version failed with two lifecycle environments

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
# ansible --version
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.2 (default, Mar 21 2019, 10:09:12) [GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]

# cat /etc/redhat-release 
Fedora release 29 (Twenty Nine)

# rpm -qa | grep theforeman
ansible-collection-theforeman-foreman-0.0.0-0.1.pre.master.20190913083800gitc924973.fc29.noarch
```

##### KATELLO/FOREMAN VERSION
```
# rpm -q tfm-rubygem-katello foreman
tfm-rubygem-katello-3.10.0.54-1.el7sat.noarch
foreman-1.20.1.35-1.el7sat.noarch

```

##### NAILGUN VERSION
```
N/A
```

##### STEPS TO REPRODUCE
1. Create org called test_org
2. Create a content view called testcv
3. Run the publish/promote task as shown below

```yaml
- hosts: localhost
  tasks:
   - name: "Publish a content view to Library, and promote that version to prod, not idempotent"
     theforeman.foreman.katello_content_view_version:
       username: "admin"
       password: "changeme"
       server_url: "https://satellite.example.com"
       content_view: "testcv"
       organization: "test_org"
       lifecycle_environments:
         - Library  
         - prod
```

##### EXPECTED RESULTS
- Publish/Promote to Library/Prod works

##### ACTUAL RESULTS
- Promotion to prod environment fails
- publish to Library worked

```
# ansible-playbook foreman_playbook.yml 

PLAY [localhost] ****************************************************

TASK [Gathering Facts] **********************************************************************
ok: [satellite.example.com]

TASK [Publish a content view to Library, and promote that version to prod, not idempotent] ***
fatal: [satellite.example.com]: FAILED! => {"changed": false, "msg": "Error while performing promote on content_view_versions: The following required parameters are missing: id"}

PLAY RECAP **********************************************************************************
localhost : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```
