### ISSUE TITLE
Password is shown in cleartext in provider_params

### ISSUE THREAD

**Issue by tmichelis** [theforeman/foreman-ansible-modules#491]
##### SUMMARY
The password for connecting to a compute resource is shown in cleartext in the ansible output.

##### ISSUE TYPE
 - Bug Report
 - Security issue

##### ANSIBLE VERSION

```
ansible 2.8.1
  config file = /home/michelis.tobias/code/ansible/infra/ansible.cfg
  configured module search path = ['/home/michelis.tobias/code/ansible/infra/foreman-ansible-modules/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 16:32:37) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
```

##### KATELLO/FOREMAN VERSION

```
tfm-rubygem-katello-3.10.0.55-1.el7sat.noarch
foreman-1.20.1.35-1.el7sat.noarch
```

##### STEPS TO REPRODUCE

Just trying to add a compute resource to a satellite server. 

```yaml
---           
- name: Manage compute resources in Satellite
  hosts: satellite
  gather_facts: false
  tasks:      
    - name: Manage compute resource
      delegate_to: localhost   
      become: false
      foreman_compute_resource:
        name: 'VCenter'
        locations: 
          - Testlocation
        organizations:
          - TestOrg
        provider: vmware
        provider_params:
          url: vcenter.example.com
          user: vcenter_user@example.com
          password: Passw0rd
        state: present
        username: admin
        server_url: satellite.example.com
        password: Passw0rd
        validate_certs: true
...           

```
The password are stored in a vault file, in our case, opposite to the example playbook
##### EXPECTED RESULTS
That the output of the password in the provider_params is not shown in clear text.

##### ACTUAL RESULTS
The password is shown in cleartext.

```
TASK [Manage compute resource] **************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
failed: [hostname -> localhost] (item={'name': 'xxx', 'state': 'present', 'locations': ['xxx', 'xxx/yyy'], 'organziations': ['xxx'], 'provider': 'vmware', 'provider_params': {'url': 'xxx', 'user': 'xxx', 'password': 'Passw0rd', 'datacenter': 'xxx'}}) => {"ansible_loop_var": "item", "changed": false, "item": {"locations": ["xxx", "xxx/yyy"], "name": "xxx", "organziations": ["xxx"], "provider": "vmware", "provider_params": {"datacenter": "xxx", "password": "Passw0rd", "url": "xxx", "user": "xxx"}, "state": "present"}, "msg": "Error while performing create on compute_resources: 500 Server Error: Internal Server Error for url: xxx/api/compute_resources"}
```
I had to X all information related to the company. Sorry for this. The internal server error is due to the fact the VCenter is not reachable. But this is not the problem. The problem is, that the password is shown.
