### ISSUE TITLE
Use similar params for katello_repository_set and katello_sync

### ISSUE THREAD

**Issue by wbclark** [theforeman/foreman-ansible-modules#498]
##### SUMMARY
When writing playbooks, it is necessary to specify two sets of variables to enable and synchronize a repository. For example:

```yaml
    product: "Red Hat Enterprise Linux Server"
    repo: "Red Hat Enterprise Linux 7 Server (RPMs)"
    repo_variants:
      - releasever: "7Server"
        basearch: "x86_64"
    repo_sync_name: "Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server"
```
katello_repository_set expects params name, product, repositories (i.e. repo_variants as defined above) while katello_sync expects params repository and product.

This is due to the fact repository_sets and repositories are named differently in Katello, however it should be possible to consistently translate between these naming conventions so that it is not necessary for the user to define a separate repo_sync_name containing redundant information under a different naming convention.

##### ISSUE TYPE
 - User Experience Improvement

**Comment by ekohl** [comment]
What if there's multiple repo variants? How would you deal with the name then?

**Comment by wbclark** [comment]
@ekohl I think the key is to pick one convention and stick to it.

If I am given:
```yaml
    repo: "Red Hat Enterprise Linux 7 Server (RPMs)"
    repo_variants:
      - releasever: "7Server"
        basearch: "x86_64"
```

I can reconstruct the below by dropping parens and appending the architecture and release:
```yaml
    repo_sync_name: "Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server"
```

And the same is true in reverse.

So regarding repo variants, do you have a strong opinion on which of the two conventions above is better for users who are using multiple variants?

**Comment by mdellweg** [comment]
We try to be very close to the api names here. What we can do is introduce aliases like `repo_name` for `repository`.
Maybe if you put

**Comment by mdellweg** [comment]
... hit the wrong button.

**Comment by mdellweg** [comment]
I do not see `repo_sync_name` anwhere.
Do you mind giving a full example (section of tasks)?
We can quite easily introduce aliases like `repo_name` for `repository`.

**Comment by wbclark** [comment]
@mdellweg sure, I am using the above variables to run tasks like below:

```yml
  tasks:
    - name: "Enable {{ repo }} repository"
      katello_repository_set:
        name: "{{ repo }}"
        product: "{{ product }}"
        repositories: "{{ repo_variants }}"
        organization: "{{ org }}"
        state: enabled
        server_url: "{{ url }}"
        username: "{{ login }}"
        password: "{{ password }}"

    - name: "Sync {{ repo }} repository"
      katello_sync:
        repository: "{{ repo_sync_name }}"
        product: "{{ product }}"
        organization: "{{ org }}"
        server_url: "{{ url }}"
        username: "{{ login }}"
        password: "{{ password }}"
```

So the `repo_sync_name` is the variable I am using for the `repository` parameter of `katello_sync`. Regardless of the different naming conventions within the Katello API, it would be much better for end users to be able to declare a single set of variables and use them consistently across the modules rather than declaring essentially redundant information.
