### ISSUE TITLE
Combine connection parameters like url and user togeteher

### ISSUE THREAD

**Issue by nesanton** [theforeman/foreman-ansible-modules#519]
##### SUMMARY
When many foreman* and katello* modules are used in a play one might find it frustrating having to scecify the very same ```server_url```, ```username```, ```password```, ```validate_certs``` all the time.
And it's not really possible to use ```module_defaults```, because one can't seem to wildcard them like foreman*.

Idea is to add an extra variable to all the modules and nest these underneath:
```yaml
connection:
  server_url:
  username:
  password:
  validate_certs:
```

This way it's only one var to feed to any module.
I guess it can coexist with the current way.

##### ISSUE TYPE
 - Feature Idea

**Comment by sean797** [comment]
Linking to https://github.com/theforeman/foreman-ansible-modules/pull/178

**Comment by mdellweg** [comment]
Also linking: https://github.com/ansible/ansible/pull/58070

**Comment by evgeni** [comment]
@mdellweg didn't I once saw a playbook of yours where you used some YaML reference or so to pass the connection parameters? It's not the same but still makes life easier.

**Comment by mdellweg** [comment]
Like here:
https://github.com/mdellweg/pulp_ansible_modules/blob/master/tests/playbooks/file_distribution.yaml#L55
Yes, but its scope is limited to one file.

**Comment by nesanton** [comment]
I learnt to live with either yaml references like @mdellweg's or this:
``` yaml
vars:
  foreman_api:
     server_url: https://blah.blah.com
     username: blah
     password: blahblah
     validate_certs: no
module_defaults:
  foreman_this: "{{ foreman_api }}"
  foreman_that: "{{ foreman_api }}"
  katello_here: "{{ foreman_api }}"
```
or the combination of two.

Anyway, closing this, because it seems to be (or going to be) sort of solvable by module grouping.
