### ISSUE TITLE
foreman_hostgroup always reports "changed" with compute_resource

### ISSUE THREAD

**Issue by nesanton** [theforeman/foreman-ansible-modules#560]
##### SUMMARY
module foreman_hostgroup is not idempotent (always reports changed=true) when used with compute_resource.

##### ISSUE TYPE
 - Bug Report1

##### ANSIBLE VERSION

```
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Apr 30 2019, 15:54:59) [GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]

```

##### KATELLO/FOREMAN VERSION

```
# rpm -q tfm-rubygem-katello foreman
tfm-rubygem-katello-3.11.2-1.el7.noarch
foreman-1.21.3-1.el7.noarch
```
##### APYPIE VERSION

```
0.0.5
```

##### STEPS TO REPRODUCE

1. create a hostgroup with non-empty compute_resource ("Deploy on" in the GUI)
2. rerun same play
3. ack "changed=true"

```yaml
- name: "Make sure Host Group exists"
  foreman_hostgroup:
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    server_url: "{{ server_url }}"
    name: "{{ hostgroup }}"
    compute_resource: "{{ compute_resource }}"
    organization: "{{ organization }}"
    state: present
  tags:
    - hostgroup

```

##### EXPECTED RESULTS

When ran for the second time in a row, the task reports changed=false

##### ACTUAL RESULTS

When ran for the second time in a row, the task reports changed=true

not sure how the tests pass, because compute_resource is used there.
