### ISSUE TITLE
Issue with smart_proxies

### ISSUE THREAD

**Issue by igramic** [theforeman/foreman-ansible-modules#596]
##### SUMMARY

When using domains and subnets module with dns_proxy option we are always getting error that 
"msg": "No data found for name=\"sat6cap02.example.com\""
But if we manually go to /api/smart_proxies?search=name=sat6cap02.example.com
correct result is returned. Also if I do same thing via satellite gui all works.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.8.3
```

##### KATELLO/FOREMAN VERSION

```
using newest from gitlab
```

##### APYPIE VERSION

```
Version: 0.2.0
```

##### STEPS TO REPRODUCE

```yaml

Just create new domain:
- name: "Create | Remove domain"
  foreman_domain:
    server_url: "https://{{ sat_server }}"
    username: "{{ sat_usr }}"
    password: "{{ sat_pass }}"
    validate_certs: False
    name: "{{ name }}"
    description: "{{ description }}"
    state: "present"
    dns_proxy: "{{ dns_proxy }}"
```

##### EXPECTED RESULTS

New domain created with DNS capsule set to proper value.

##### ACTUAL RESULTS

```

```
