### ISSUE TITLE
foreman_host_power: Unknown action 'power_status' on foreman < 1.22.0

### ISSUE THREAD

**Issue by nesanton** [theforeman/foreman-ansible-modules#652]
##### SUMMARY
Using foreman_host_power on foreman version older than 1.22.0 (Satellite older than 6.6) fails with "Unknown action 'power_status'".
Latest changes to the module rely on the ```power_status``` action that was added per https://projects.theforeman.org/issues/25436 to foreman 1.22.0

##### ISSUE TYPE
 - Bug Report

##### KATELLO/FOREMAN VERSION

```
foreman < 1.22.0
satellite < 6.6
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - theforeman.foreman.foreman_host_power:
        server_url: https://foreman-1-20.example.com
        username: admin
        password: changeme
        validate_certs: no
        hostname: testhost.example.com
        state: on
...
```

##### EXPECTED RESULTS

Host is powered on

##### ACTUAL RESULTS

"Unknown action 'power_status'"

```

```
