### ISSUE TITLE
I should be able to add multiple rules to a content view filter

### ISSUE THREAD

**Issue by jwbernin** [theforeman/foreman-ansible-modules#695]
##### SUMMARY

The current model in use in katello_content_view_filter only allows the addition of a single rule per filter item. If the same call is reissued with the same filter name and a different rule, the rule is replaced rather than appended to. I would like to be able to either append to a rule with a follow-on play, or I would like to be able to specify multiple rules within a given filter.

##### ISSUE TYPE
 - Feature Idea

**Comment by sean797** [comment]
I think if you supply the same name, but a different rule_name this should
work?

**Comment by evgeni** [comment]
Yepp, setting different `rule_name`s should work. It just defaults to the same value as the filter name itself.

**Comment by jwbernin** [comment]
`rule_name` is an alias of `package_name` so when I set a `rule_name`, I get `[WARNING]: Both option rule_name and its alias package_name are set.` and the rule is replaced, not appended to.

**Comment by evgeni** [comment]
ah, can you post your whole playbook then to reproduce please?

**Comment by jwbernin** [comment]
```
---
- name: Add filters
  hosts: localhost

  tasks:
    - name: Add filter
      katello_content_view_filter:
        username: admin
        password: password
        server_url: "https://satellite.example.com"
        validate_certs: false
        name: "pkg filter 1"
        organization: MyOrg
        content_view: rhel7
        filter_type: "rpm"
        package_name: "389-ds-base"
        version: "0:1.3.1.6-26.el7_0"
        inclusion: true

    - name: Add filter
      katello_content_view_filter:
        username: admin
        password: password
        server_url: "https://satellite.example.com"
        validate_certs: false
        name: "pkg filter 1"
        organization: MyOrg
        content_view: rhel7
        filter_type: "rpm"
        package_name: "389-ds-base"
        version: "0:1.3.3.1-13.el7"
        inclusion: true
```
