### ISSUE TITLE
katello_repository_set: possible regression

### ISSUE THREAD

**Issue by jwbernin** [theforeman/foreman-ansible-modules#756]
##### SUMMARY
A playbook to enable RH CDN repositories that worked circa 0.3.0 no longer works, emitting an error "Failed to show resource: id (2456): Must be a number."

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.5
  config file = /nfshome/jberning/ansible/ansible.cfg
  configured module search path = ['/nfshome/jberning/Projects/foreman-ansible-modules/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Oct 11 2019, 15:04:54) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]

```

##### KATELLO/FOREMAN VERSION

```
tfm-rubygem-katello-3.12.0.37-1.el7sat.noarch
foreman-1.22.0.36-1.el7sat.noarch
```

##### APYPIE VERSION

```
$ pip3 show apypie | grep Version
Version: 0.0.2

```

##### STEPS TO REPRODUCE

```
---
- name: enable repos on Satellite
  hosts: localhost
  vars:
    satellite_host: newsat.ncphotography.lan
    satellite_user: admin
    satellite_password: admin
    org_name: NCP
    repos:
      - name: rhel-7-server-ansible-2.6-rpms
        arch: x86_64
      - name: ansible-2.8-for-rhel-8-x86_64-rpms
        arch: x86_64
      - name: rhel-7-server-extras-rpms
        arch: x86_64
      - name: rhel-7-server-optional-rpms
        arch: x86_64
        release: 7Server
      - name: rhel-7-server-rpms
        arch: x86_64
        release: 7Server


  tasks:

    - name: Enable Upstream repositories
      katello_repository_set:
        username: "{{ satellite_user }}"
        password: "{{ satellite_password }}"
        server_url: "https://{{ satellite_host }}"
        verify_ssl: false
        organization: "{{ org_name }}"
        label: "{{ item.name }}"
        repositories:
          - releasever: "{{ item.release | default ('')}}"
            basearch: "{{ item.arch }}"
        state: enabled
      loop: "{{ repos }}"

```

##### EXPECTED RESULTS

Expected to have the repositories listed enabled
##### ACTUAL RESULTS

Each item in the loop gives a very similar error message, below is the last error message emitted.

```
The full traceback is:
  File "/tmp/ansible_katello_repository_set_payload_7ycblznz/ansible_katello_repository_set_payload.zip/ansible/module_utils/foreman_helper.py", line 49, in inner
    return f(self, *args, **kwargs)
  File "/tmp/ansible_katello_repository_set_payload_7ycblznz/ansible_katello_repository_set_payload.zip/ansible/module_utils/foreman_helper.py", line 340, in show_resource
    return self._resource_call(resource, 'show', params)
  File "/tmp/ansible_katello_repository_set_payload_7ycblznz/ansible_katello_repository_set_payload.zip/ansible/module_utils/foreman_helper.py", line 324, in _resource_call
    return self._resource(resource).call(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/apypie/resource.py", line 30, in call
    return self.api.call(self.name, action, params, headers, options)
  File "/usr/local/lib/python3.6/site-packages/apypie/api.py", line 157, in call
    action.validate(params)
  File "/usr/local/lib/python3.6/site-packages/apypie/action.py", line 53, in validate
    self._validate(self.params, values)
  File "/usr/local/lib/python3.6/site-packages/apypie/action.py", line 87, in _validate
    raise ValueError("{} ({}): {}".format(param, value, param_description.validator))
failed: [localhost] (item={'name': 'rhel-7-server-rpms', 'arch': 'x86_64', 'release': '7Server'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "all_repositories": null,
            "label": "rhel-7-server-rpms",
            "name": null,
            "organization": "NCP",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "product": null,
            "repositories": [
                {
                    "basearch": "x86_64",
                    "releasever": "7Server"
                }
            ],
            "server_url": "https://newsat.ncphotography.lan",
            "state": "enabled",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "validate_certs": false,
            "verify_ssl": false
        }
    },
    "item": {
        "arch": "x86_64",
        "name": "rhel-7-server-rpms",
        "release": "7Server"
    },
    "msg": "Failed to show resource: id (2456): Must be a number."
}

```
