### ISSUE TITLE
Add possibility to change download_policy for Red Hat repositories

### ISSUE THREAD

**Issue by knumskull** [theforeman/foreman-ansible-modules#819]
##### SUMMARY
It's not possible today to enable repositry-sets and define the download_policy for Red Hat Repos.

It should be possible to change the policy.

Using `katello_repository` module does not work
```
  - name: "Set download policy to immediate for Kickstart Repos"
    theforeman.foreman.katello_repository:
      username: "{{ satellite_username }}"
      password: "{{ satellite_password }}"
      server_url: "{{ satellite_url }}"
      validate_certs: "{{ validate_certs }}"
      organization: "{{ satellite_organization }}"
      name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream (Kickstart)"
      content_type: "yum"
      product: "Red Hat Enterprise Linux for x86_64"
      download_policy: immediate
```

```
TASK [Set download policy to immediate for Kickstart Repos] ************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "error": {"displayMessage": "Red Hat products cannot be manipulated.", "errors": ["Red Hat products cannot be manipulated."]}, "msg": "Error while performing create on repositories: 400 Client Error: Bad Request for url: https://satellite.example.com/katello/api/repositories"}
```
##### ISSUE TYPE
 - Feature Idea

**Comment by evgeni** [comment]
this is possible in the UI, so def a bug, but might be API instead of FAM.

**Comment by evgeni** [comment]
Reading the code, this error should only be raised when you try to _create_ a repo in an RH product. So may be your repo name is wrong and it does not find it, so it tries to create it?

**Comment by knumskull** [comment]
My repo is inside a RH product, as I want to have Kickstart repos synced immediate. 
For example, following two Repos I would like to have synced immediate.

```
- { product: "Red Hat Enterprise Linux for x86_64", name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream Kickstart 8.1"}
- { product: "Red Hat Enterprise Linux for x86_64", name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.1"}
```
As you already wrote, I can change the download-policy via UI.

Based on [1] the download_policy should be changeable using API, but I'm getting error, when testing with following snipped:

```
# curl -request PUT --insecure --user admin:redhat01 \
https://satellite.example.com/katello/api/repositories/283 -d '{"download_policy": "on_demand"}'


<body>
  <!-- This file lives in public/404.html -->
  <div class="dialog">
    <div>
      <h1>The page you were looking for doesn't exist.</h1>
      <p>You may have mistyped the address or the page may have moved.</p>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>
```

Repo is configured like following:

```
 {                                                                                                                                                                                                                                               
...                                                                                                                                                   
    "promoted": false,                                                                                                                                                                                                                          
    "content_view_version_id": 1,                                                                                                                                                                                                               
    "library_instance_id": null,                                                                                                                                                                                                                
    "distribution_version": "8.1.0",                                                                                                                                                                                                            
    "distribution_arch": "x86_64",                                                                                                                                                                                                              
    "distribution_bootable": true,                                                                                                                                                                                                              
    "distribution_family": "Red Hat Enterprise Linux",                                                                                                                                                                                          
    "distribution_variant": "BaseOS",                                                                                                                                                                                                           
...                                                                                                                                                                                                                                                                                                                                                 
    "id": 283,                                                                                                                                                                                                                                  
    "name": "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.1",                                                                                                                                                                     
    "label": "Red_Hat_Enterprise_Linux_8_for_x86_64_-_BaseOS_Kickstart_8_1",                                                                                                                                                                    
    "description": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    "content_type": "yum",                                                                                                                                                                                                                      
    "url": "https://cdn.redhat.com/content/dist/rhel8/8.1/x86_64/baseos/kickstart",                                                                                                                                                             
    "arch": "noarch",                                                                                                                                                                                                                           
    "content_id": "7421",                                                                                                                                                                                                                       
    "major": 8,                                                                                                                                                                                                                                 
    "minor": "8.1",                                                                                                                                                                                                                             
    "product": {                                                                                                                                                                                                                                
        "id": 9,                                                                                                                                                                                                                                
        "cp_id": "479",                                                                                                                                                                                                                         
        "name": "Red Hat Enterprise Linux for x86_64",                                                                                                                                                                                          
        "orphaned": false,                                                                                                                                                                                                                      
        "redhat": true,                                                                                                                                                                                                                         
        "sync_plan": {                                                                                                                                                                                                                          
            "name": "Weekly Product Sync",                                                                                                                                                                                                      
            "description": null,                                                                                                                                                                                                                
            "sync_date": "2020-01-01 00:00:00 UTC",                                                                                                                                                                                             
            "interval": "weekly",                                                                                                                                                                                                               
            "next_sync": "2020-05-27 00:00:00 UTC"                                                                                                                                                                                              
        }                                                                                                                                                                                                                                       
    },                                                                    
   "verify_ssl_on_sync": true,                             
    "unprotected": true,                                    
    "checksum_type": null,                                  
    "download_policy": "immediate",                                                   
...
```


[1]: https://theforeman.org/plugins/katello/3.4/api/apidoc/v2/repositories/update.html

**Comment by jwbernin** [comment]
I'm able to set the download policy on RH CDN repos as follows:

```
    - name: get all repositories
      foreman_search_facts:
        username: "{{ satAdmin }}"
        password: "{{ satPass }}"
        server_url: "https://{{ inventory_hostname }}"
        validate_certs: false
        resource: repositories
      register: repositories
      delegate_to: localhost

    - name: Set download policy
      katello_repository:
        username: "{{ satAdmin }}"
        password: "{{ satPass }}"
        server_url: "https://{{ inventory_hostname }}"
        verify_ssl: false
        organization: "{{ satOrg }}"
        name: "{{ item.name }}"
        download_policy: immediate
        content_type: yum
        product: "{{ item.product.name }}"
      loop: "{{ repositories.resources }}"
      delegate_to: localhost
```

The play looks identical to the non-working example in the original post - perhaps you're on an older version of these modules?
