### ISSUE TITLE
document how to enable multiple repositories

### ISSUE THREAD

**Issue by jwbernin** [theforeman/foreman-ansible-modules#822]
##### SUMMARY

I have a playbook that iterates through repositories to enable. Some repositories have a releasever, some have a basearch, some have neither, some have both. In the third case, I have to have a separate play to enable those repositories.

The snippet of concern from my playbook that is working:
```
    - name: Ensure repos are enabled
      katello_repository_set:
        username: "{{ satAdmin }}"
        password: "{{ satPass }}"
        server_url: "https://{{ inventory_hostname }}"
        verify_ssl: false
        organization: "{{ satOrg }}"
        label: "{{ item.label }}"
        repositories: "{{ item.repositories | default(omit)}}"
        state: enabled
      loop: "{{ cdn_repos }}"
      when: item.repositories is defined
      delegate_to: localhost

    - name: Ensure repos are enabled
      katello_repository_set:
        username: "{{ satAdmin }}"
        password: "{{ satPass }}"
        server_url: "https://{{ inventory_hostname }}"
        verify_ssl: false
        organization: "{{ satOrg }}"
        label: "{{ item.label }}"
        all_repositories: yes
        state: enabled
      loop: "{{ cdn_repos }}"
      when: item.repositories is not defined
      delegate_to: localhost
```

What I would like:
```
    - name: Ensure repos are enabled
      katello_repository_set:
        username: "{{ satAdmin }}"
        password: "{{ satPass }}"
        server_url: "https://{{ inventory_hostname }}"
        verify_ssl: false
        organization: "{{ satOrg }}"
        label: "{{ item.label }}"
        repositories: "{{ item.repositories | default('all')}}"
        state: enabled
      loop: "{{ cdn_repos }}"
      delegate_to: localhost
```

##### ISSUE TYPE
 - Feature Idea

**Comment by evgeni** [comment]
using "repositories: all" would make the ansible argument parser less helpfull for us, but I think we can come up with a doc example how you can achieve that in one task. I'll try to provide this example next week.

**Comment by evgeni** [comment]
How about the following?

```yaml
    - name: Ensure repos are enabled
      katello_repository_set:
        username: "{{ satAdmin }}"
        password: "{{ satPass }}"
        server_url: "https://{{ inventory_hostname }}"
        verify_ssl: false
        organization: "{{ satOrg }}"
        label: "{{ item.label }}"
        repositories: "{{ item.repositories | default(omit) }}"
        all_repositories: "{{ item.repositories is not defined }}"
        state: enabled
      loop: "{{ cdn_repos }}"
      delegate_to: localhost
```

The important part is:
```yaml
        repositories: "{{ item.repositories | default(omit) }}"
        all_repositories: "{{ item.repositories is not defined }}"
```
this will set `repositories` if it's defined, and otherwise `all_repositories` will be `true`
