### ISSUE TITLE
Missing module to create HTTP Proxy

### ISSUE THREAD

**Issue by knumskull** [theforeman/foreman-ansible-modules#867]
##### SUMMARY
While it's possible to set a default proxy for the foreman instance, it's not possible to create a HTTP Proxy for that purpose.

Currently iit's possible to workaround the issue by following snippet, but it's not really idempotent.

```
  - name: Check for proxy existence
    shell: hammer http-proxy info --name "{{ default_http_proxy }}"
    register: result
    failed_when: result.rc == 123412341234
    changed_when: result.rc == 345678

  - name: Update proxy if needed
    shell: hammer http-proxy update --name "{{ default_http_proxy }}"  --username "{{ http_proxy_user }}" --password "{{ http_proxy_passwd }}" --url "{{ http_proxy }}" --location "{{ location }}"
    when: result.rc == 0

  - name: Define http proxy
    shell: hammer http-proxy create --name "{{ default_http_proxy }}" --username "{{ http_proxy_user }}" --password "{{ http_proxy_passwd }}" --url "{{ http_proxy }}" --location "{{ location }}"
    when: result.rc != 0

  - name: Set default https proxy
    setting:
      username: "{{ sat_user }}"
      password: "{{ sat_passwd }}"
      server_url: "{{ sat_url }}"
      name: "content_default_http_proxy"
      value: "{{ default_http_proxy }}"
    when: default_http_proxy is defined
```

##### ISSUE TYPE
 - Feature Idea
