### ISSUE TITLE
naming content views modules

### ISSUE THREAD

**Issue by gregswift** [theforeman/foreman-ansible-modules#87]
Hey! guess what.. i thought of something crappy.

We agreed to have composite_content_view as a separate module, which can make things easier for consumers of the modules. its way more specific (i'm kewl with it).

So in general our workflow is this:

1) Create a bunch of products with modules
2) Create dedicated content views for a thing (CentOS, PostgreSQL, Zabbix, Product1, Product2, etc)
3) Version the content views
4) Create composite content views for groups that need them (Generic, Product1, Product2)
5) Add versions of content views to the composite view
6) Cut releases of the composite view
7) Promote version of the composite view

So the playbook for pushing a new version of the CentOS repositories through the Generic CCV with ansible will look something like this

```
- tasks:
  - katello_publish:
      content_view: CV CentOS
  - katello_composite_content_view:
      name: CCV Generic
      content_views:
        - name: CV CentOS
          version: [umm how do i know what got cut?]
  - katello_publish:
      content_view: CCV Generic
  - katello_content_view_version_promote:
      content_view: CCV Generic
      version: [umm what is it?]
      to_environment: Library
  - katello_content_view_version_promote:
      content_view: CCV Generic
      version: [umm what is it?]
      from_environment: Library
      to_environment: Staging
```
It feels to me like handling the CCV inside the CV modules invalidates the reasoning for having composite as a separate module.
