### ISSUE TITLE
updating an os with the operatingsystem module always fails

### ISSUE THREAD

**Issue by RobVerduijn** [theforeman/foreman-ansible-modules#946]
##### SUMMARY
When using the operatingsystem module you get an error when you try to update an operating system in katello
Adding a new operating system to katello works fine.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/rob/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
```

##### KATELLO/FOREMAN VERSION

```
tfm-rubygem-katello-3.16.0-1.el7.noarch
foreman-2.1.2-1.el7.noarch
```

##### APYPIE VERSION

```
Version: 0.2.2
```

##### STEPS TO REPRODUCE

ensure the centos 8 repositories have been synced.
Somehow this always results in an os called 'CentOS_Linux 8' which keeps returning when removed after every sync.
see playbook below on the reproducer

```yaml
---
- name: setup katello
  hosts: localhost
  gather_facts: true
  collections:
  - theforeman.foreman
  vars:
    katello_admin_user: admin
    katello_admin_password: redhat
    katello_server_url: 'http://katallo.linux.lab'

  tasks:
  - name: "Create operating system"
    theforeman.foreman.operatingsystem:
      username: "{{ katello_admin_user }}"
      password: "{{ katello_admin_password }}"
      server_url: "{{ katello_server_url }}"
      validate_certs: false
      name: CentOS
      os_family: Redhat
      major: '8'
      minor: '1.1911'
      password_hash: SHA256
 
  - name: "Update operating system for new release"
    theforeman.foreman.operatingsystem:
      username: "{{ katello_admin_user }}"
      password: "{{ katello_admin_password }}"
      server_url: "{{ katello_server_url }}"
      validate_certs: false
      name: CentOS
      os_family: Redhat
      major: '8'
      minor: '2.2004'
      password_hash: SHA256
 
```

##### EXPECTED RESULTS

The operating system should be updated with the new values, the same way you can do when you edit the os in the gui.

##### ACTUAL RESULTS

Using module file /home/rob/.ansible/collections/ansible_collections/theforeman/foreman/plugins/modules/installation_medium.py
Pipelining is enabled.
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 && sleep 0'
failed: [localhost] (item={'name': 'CentOS 8', 'operatingsystems': ['CentOS 8'], 'path': 'http://katello.linux.lab/pulp/repos/cloudlab/Library/custom/centos_8/CentOS_8_BaseOS_x86_64/'}) => {
    "ansible_loop_var": "installation_medium",
    "changed": false,
    "installation_medium": {
        "name": "CentOS 8",
        "operatingsystems": [
            "CentOS 8"
        ],
        "path": "http://katello.linux.lab/pulp/repos/cloudlab/Library/custom/centos_8/CentOS_8_BaseOS_x86_64/"
    },
    "invocation": {
        "module_args": {
            "locations": [
                "zolder"
            ],
            "name": "CentOS 8",
            "operatingsystems": [
                "CentOS 8"
            ],
            "organizations": [
                "Zolder Cloud Lab"
            ],
            "os_family": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "path": "http://katello.linux.lab/pulp/repos/cloudlab/Library/custom/centos_8/CentOS_8_BaseOS_x86_64/",
            "server_url": "https://katello.linux.lab",
            "state": "present",
            "updated_name": null,
            "username": "admin",
            "validate_certs": false
        }
    },
    "msg": "Found too many (2) results while searching for operatingsystems with title~\"CentOS 8\""
}

```

```
