### ISSUE TITLE
Newly created locations are not accessible for normal user

### ISSUE THREAD

**Issue by cmeissner** [theforeman/foreman-ansible-modules#948]
##### SUMMARY
If we create a new location via ansible location module

The newly created location cannot be seen by any user except for admins. We don't see any chance to configure valid users or the `all user` flag via ansible. 

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
Version: 2.9.10
```
##### KATELLO/FOREMAN VERSION
2.1.0

##### APYPIE VERSION
```
Version: 0.2.2
```

##### STEPS TO REPRODUCE
```yaml
- name: "Create Location"
  theforeman.foreman.location:
    username: "{{ foreman_admin }}"
    password: "{{ foreman_admin_password }}"
    server_url: "{{ foreman_url }}"
    validate_certs: "{{ validate_certs }}"
    name: "{{ location.name }}"
    organizations: "{{ location.organizations }}"
    state: "{{ location.state | default('present') }}"
```

##### EXPECTED RESULTS
There should be a possibility to set users and/or the `all users` flag

##### ACTUAL RESULTS
We have to configure the allowed users by hand.
