### ISSUE TITLE
Compute attributes needs to be dictionary, they do not accept lists

### ISSUE THREAD

**Issue by ezr-ondrej** [theforeman/foreman-ansible-modules#954]
Compute attributes `interfaces_attributes` and `volumes_attributes` needs to be dicts. These are really dicts in form of:
```yaml
interfaces_attributes:
  '0':
    type: VirtualE1000
    network: dvportgroup-107
  '1':
    type: VirtualE1000
    network: dvportgroup-106
```
It's a bit ugly and strange. Maybe it's a good idea to:

1. Document the correct format and possible parameters of `vm_attrs` dict
2. Make the nested parameters a bit more convenient and provide the both data structures as lists instead of dicts.
