### ISSUE TITLE
wait_for feature for theforeman.foreman.host

### ISSUE THREAD

**Issue by gardar** [theforeman/foreman-ansible-modules#961]
##### SUMMARY

Please consider adding wait_for feature(s) for the host module, the feature would be used to get the ansible playbook to wait until the host is created/built or modifications to the host are successfully applied.

The [vmware_guest_module](https://docs.ansible.com/ansible/latest/modules/vmware_guest_module.html) can be used as a inspiration as it has two such options for waiting:
  * **wait_for_customization** - Wait until vCenter detects all guest customizations as successfully completed.
When enabled, the VM will automatically be powered on.
  * **wait_for_ip_address** - Wait until vCenter detects an IP address for the virtual machine. This requires vmware-tools (vmtoolsd) to properly work after creation. vmware-tools needs to be installed on the given virtual machine in order to work with this parameter.

Using a separate task with [wait_for_connection](https://docs.ansible.com/ansible/latest/modules/wait_for_connection_module.html#wait-for-connection-module) is not always possible since the host could be deployed on a network that's not accessible from where the foreman playbook is being run.

If I could query the build status of the host in a separate task then I guess that would be a acceptable workaround, but I haven't found a way to do that with the current modules.

--

##### ISSUE TYPE
 - Feature Idea

**Comment by gardar** [comment]
Found a good workaround, creating a task with a "until" loop that looks up the host by name and checks if the status of the host is installed and that it's got a IP address.
I'm verifying that it's got a IP in addition to being installed as the host seems to also get the "Installed" status when it's booted into the foreman discovery image

```yaml
- name: "Check if VM is built and wait if it's not (max 10 minutes)"                                      
  theforeman.foreman.resource_info:                                                                       
    username: "{{ satellite_server_usr }}"                                                                
    password: "{{ satellite_server_psw }}"                                                                
    server_url: "https://{{ satellite_server_fqdn }}"                                                     
    validate_certs: false                                                                                 
    full_details: true                                                                                    
    search: name = "{{ satellite_host_name }}"                                                            
    resource: hosts                                                                                       
  register: build_post                                                                                    
  until: build_post.resources[0].build_status_label == "Installed" and build_post.resources[0].ip | ipaddr
  retries: 150                                                                                            
  delay: 15                                                                                               

```
