### ISSUE TITLE
Hostgroup parameters not set

### ISSUE THREAD

**Issue by Thulium-Drake** [theforeman/foreman-ansible-modules#985]
##### SUMMARY

When setting Hostgroup parameters (among which kt_activation_keys) with a collection higher then 1.0.0, they are not set.

I don't know which version introduced it, but the changelog suggests 1.2.0. 

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.10.0
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

```

##### KATELLO/FOREMAN VERSION

```
tfm-rubygem-katello-3.16.0-1.el7.noarch
foreman-2.1.2-1.el7.noarch
```

##### APYPIE VERSION

```
Version: 0.2.2
```

##### STEPS TO REPRODUCE

```yaml
- name: "Create a Hostgroup"
  hostgroup:
    name: "new_hostgroup"
    architecture: "architecture_name"
    operatingsystem: "operatingsystem_name"
    medium: "media_name"
    ptable: "Partition_table_name"
    server_url: "https://foreman.example.com"
    username: "admin"
    password: "secret"
    parameters:
      - name: kt_activation_keys
        value: Some-AK
    state: present
```

##### EXPECTED RESULTS

Paramters to be defined
##### ACTUAL RESULTS

```
changed: [foreman.infra.example.com] => (item={'name': 'CentOS7-Base', 'arch': ['x86_64'], 'network': 'Production', 'root_pass': 'somepassword', 'dns_zone': 'prod.example.com', 'smart_proxy': 'foreman.infra.example.com', 'ptable': 'Kickstart default', 'lifecycle': 'Production', 'pxe_loader': 'PXELinux BIOS', 'os': 'CentOS 7', 'kickstart': True, 'kickstart_repo': 'CentOS7-Base', 'parameters': [{'name': 'kt_activation_keys', 'value': 'CentOS7-Base-Production'}, {'name': 'autopart_options', 'value': '--nohome'}, {'name': 'remote_execution_create_user', 'value': 'true', 'parameter_type': 'boolean'}, {'name': 'remote_execution_ssh_user', 'value': 'ansible'}, {'name': 'remote_execution_effective_user_method', 'value': 'sudo'}, {'name': 'remote_execution_ssh_keys', 'value': 'somekeys'}, {'name': 'enable-epel', 'value': 'false', 'parameter_type': 'boolean'}]}) => changed=true 
  ansible_loop_var: hostgroup
  entity:
    hostgroups:
    - all_puppetclasses: []
      ancestry: null
      architecture_id: 1
      architecture_name: x86_64
      compute_profile_id: null
      compute_profile_name: null
      compute_resource_id: null
      compute_resource_name: null
      config_groups: []
      created_at: 2020-09-28 10:02:24 UTC
      description: Managed by Ansible, your changes will be lost
      domain_id: 4
      domain_name: prod.example.com
      environment_id: null
      environment_name: null
      id: 7
      inherited_architecture_id: null
      inherited_compute_profile_id: null
      inherited_compute_resource_id: null
      inherited_domain_id: null
      inherited_environment_id: null
      inherited_medium_id: null
      inherited_operatingsystem_id: null
      inherited_ptable_id: null
      inherited_puppet_ca_proxy_id: null
      inherited_puppet_proxy_id: null
      inherited_pxe_loader: null
      inherited_realm_id: null
      inherited_subnet6_id: null
      inherited_subnet_id: null
      locations:
      - description: null
        id: 4
        name: DC1
        title: DC1
      - description: null
        id: 5
        name: DC2
        title: DC2
      medium_id: null
      medium_name: null
      name: CentOS7-Base-Production
      operatingsystem_id: 1
      operatingsystem_name: CentOS 7
      organizations:
      - description: Managed by Ansible, your changes will be lost
        id: 3
        name: Example-Org
        title: Example-Org
      parameters: []
      parent_id: null
      parent_name: null
      ptable_id: 116
      ptable_name: Kickstart default
      puppet_ca_proxy: null
      puppet_ca_proxy_id: null
      puppet_ca_proxy_name: null
      puppet_proxy: null
      puppet_proxy_id: null
      puppet_proxy_name: null
      puppetclasses: []
      pxe_loader: PXELinux BIOS
      realm_id: null
      realm_name: null
      subnet6_id: null
      subnet6_name: null
      subnet_id: 4
      subnet_name: Production
      template_combinations: []
      title: CentOS7-Base-Production
      updated_at: 2020-09-28 12:32:37 UTC
    parameters:
    - created_at: 2020-09-28 12:32:37 UTC
      id: 63
      name: remote_execution_ssh_user
      parameter_type: string
      priority: 60
      updated_at: 2020-09-28 12:32:37 UTC
      value: ansible
    - created_at: 2020-09-28 12:32:37 UTC
      id: 64
      name: kt_activation_keys
      parameter_type: string
      priority: 60
      updated_at: 2020-09-28 12:32:37 UTC
      value: CentOS7-Base-Production
    - created_at: 2020-09-28 12:32:37 UTC
      id: 65
      name: remote_execution_effective_user_method
      parameter_type: string
      priority: 60
      updated_at: 2020-09-28 12:32:37 UTC
      value: sudo
    - created_at: 2020-09-28 12:32:37 UTC
      id: 66
      name: remote_execution_create_user
      parameter_type: boolean
      priority: 60
      updated_at: 2020-09-28 12:32:37 UTC
      value: true
    - created_at: 2020-09-28 12:32:37 UTC
      id: 67
      name: enable-epel
      parameter_type: boolean
      priority: 60
      updated_at: 2020-09-28 12:32:37 UTC
      value: false
    - created_at: 2020-09-28 12:32:37 UTC
      id: 68
      name: remote_execution_ssh_keys
      parameter_type: string
      priority: 60
      updated_at: 2020-09-28 12:32:37 UTC
      value: "some keys"
    - created_at: 2020-09-28 12:32:37 UTC
      id: 69
      name: autopart_options
      parameter_type: string
      priority: 60
      updated_at: 2020-09-28 12:32:37 UTC
      value: --nohome
  hostgroup:
    arch:
    - x86_64
    dns_zone: prod.example.com
    kickstart: true
    kickstart_repo: CentOS7-Base
    lifecycle: Production
    name: CentOS7-Base
    network: Production
    os: CentOS 7
    parameters:
    - name: kt_activation_keys
      value: CentOS7-Base-Production
    - name: autopart_options
      value: --nohome
    - name: remote_execution_create_user
      parameter_type: boolean
      value: 'true'
    - name: remote_execution_ssh_user
      value: ansible
    - name: remote_execution_effective_user_method
      value: sudo
    - name: remote_execution_ssh_keys
      value: "a bunch of keys"
    - name: enable-epel
      parameter_type: boolean
      value: 'false'
    ptable: Kickstart default
    pxe_loader: PXELinux BIOS
    root_pass: somepassword
    smart_proxy: foreman.infra.example.com
```
